/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accounts_fundingSources_create } from "../../funcs/accounts_fundingSources_create.js";
import { CreateFundingSourceForAccountRequestBody$zodSchema } from "../../models/components/createfundingsourceforaccountrequestbody.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateFundingSourceForAccountRequestBody$zodSchema,
};

export const tool$accounts_fundingSources_create: ToolDefinition<typeof args> =
  {
    name: "accounts-funding-sources-create",
    description: `Create a funding source for an account

Create a funding source for an account`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await accounts_fundingSources_create(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
