/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accounts_transfers_list } from "../../funcs/accounts_transfers_list.js";
import { ListAndSearchTransfersRequest$zodSchema } from "../../models/operations/listandsearchtransfers.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListAndSearchTransfersRequest$zodSchema,
};

export const tool$accounts_transfers_list: ToolDefinition<typeof args> = {
  name: "accounts-transfers-list",
  description: `List and search transfers for an account

List and search transfers for an account`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await accounts_transfers_list(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
