/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accountsFundingSourcesList } from "../../funcs/accountsFundingSourcesList.js";
import { ListFundingSourcesRequest$zodSchema } from "../../models/listfundingsourcesop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListFundingSourcesRequest$zodSchema,
};

export const tool$accountsFundingSourcesList: ToolDefinition<typeof args> = {
  name: "accounts-funding-sources-list",
  description: `List funding sources for an account

Get a list of all funding sources associated with a specific Main Dwolla Account. This endpoint returns both bank accounts and balance funding sources, with detailed information about each funding source's status, type, and available processing channels.
`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await accountsFundingSourcesList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
