/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accountsMassPaymentsList } from "../../funcs/accountsMassPaymentsList.js";
import { ListMassPaymentsRequest$zodSchema } from "../../models/listmasspaymentsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListMassPaymentsRequest$zodSchema,
};

export const tool$accountsMassPaymentsList: ToolDefinition<typeof args> = {
  name: "accounts-mass-payments-list",
  description: `List account mass payments

Returns a paginated list of mass payments created by your Main Dwolla account. Results are sorted by creation date in descending order (newest first) and can be filtered by correlation ID.`,
  scopes: ["read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await accountsMassPaymentsList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
