/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accounts_exchanges_list } from "../../funcs/accounts_exchanges_list.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$accounts_exchanges_list: ToolDefinition = {
  name: "accounts-exchanges-list",
  description: `List exchanges for an account

List exchanges for an account`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await accounts_exchanges_list(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
