/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { beneficialOwners_certifyOwnership } from "../../funcs/beneficialOwners_certifyOwnership.js";
import { CertifyBeneficialOwnershipForCustomerRequest$zodSchema } from "../../models/operations/certifybeneficialownershipforcustomer.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CertifyBeneficialOwnershipForCustomerRequest$zodSchema,
};

export const tool$beneficialOwners_certifyOwnership: ToolDefinition<
  typeof args
> = {
  name: "beneficial-owners-certify-ownership",
  description: `Certify beneficial ownership status

certify beneficial ownership status`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await beneficialOwners_certifyOwnership(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
