/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { beneficialOwners_documents_list } from "../../funcs/beneficialOwners_documents_list.js";
import { ListBeneficialOwnerDocumentsRequest$zodSchema } from "../../models/operations/listbeneficialownerdocuments.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListBeneficialOwnerDocumentsRequest$zodSchema,
};

export const tool$beneficialOwners_documents_list: ToolDefinition<typeof args> =
  {
    name: "beneficial-owners-documents-list",
    description: `List document for beneficial owner

List document for beneficial owner`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await beneficialOwners_documents_list(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
