/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { beneficialOwners_documents_create } from "../../funcs/beneficialOwners_documents_create.js";
import { CreateBeneficialOwnerDocumentRequest$zodSchema } from "../../models/operations/createbeneficialownerdocument.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateBeneficialOwnerDocumentRequest$zodSchema,
};

export const tool$beneficialOwners_documents_create: ToolDefinition<
  typeof args
> = {
  name: "beneficial-owners-documents-create",
  description: `Create a document for beneficial owner

Create a document for beneficial owner`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await beneficialOwners_documents_create(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
