/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { beneficialOwners_get } from "../../funcs/beneficialOwners_get.js";
import { RetrieveBeneficialOwnerRequest$zodSchema } from "../../models/operations/retrievebeneficialowner.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: RetrieveBeneficialOwnerRequest$zodSchema,
};

export const tool$beneficialOwners_get: ToolDefinition<typeof args> = {
  name: "beneficial-owners-get",
  description: `Retrieve beneficial owner

Retrieve details for a single beneficial owner`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await beneficialOwners_get(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
