/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { beneficialOwners_update } from "../../funcs/beneficialOwners_update.js";
import { UpdateBeneficialOwnerRequest$zodSchema } from "../../models/operations/updatebeneficialowner.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateBeneficialOwnerRequest$zodSchema,
};

export const tool$beneficialOwners_update: ToolDefinition<typeof args> = {
  name: "beneficial-owners-update",
  description: `Update beneficial owner

Update beneficial owner`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await beneficialOwners_update(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
