/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { beneficialOwners_delete } from "../../funcs/beneficialOwners_delete.js";
import { DeleteBeneficialOwnerRequest$zodSchema } from "../../models/operations/deletebeneficialowner.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteBeneficialOwnerRequest$zodSchema,
};

export const tool$beneficialOwners_delete: ToolDefinition<typeof args> = {
  name: "beneficial-owners-delete",
  description: `Delete beneficial owner

Delete beneficial owner`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await beneficialOwners_delete(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
