/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { businessClassificationsGet } from "../../funcs/businessClassificationsGet.js";
import { RetrieveBusinessClassificationRequest$zodSchema } from "../../models/retrievebusinessclassificationop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: RetrieveBusinessClassificationRequest$zodSchema,
};

export const tool$businessClassificationsGet: ToolDefinition<typeof args> = {
  name: "business-classifications-get",
  description: `Retrieve a business classification

Returns a specific business classification with its embedded industry classifications. Use this endpoint to browse available industry options within a business category and obtain the industry classification ID required for the businessClassification parameter when creating business verified customers.`,
  scopes: ["read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await businessClassificationsGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
