/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersBeneficialOwnersList } from "../../funcs/customersBeneficialOwnersList.js";
import { ListBeneficialOwnersForCustomerRequest$zodSchema } from "../../models/listbeneficialownersforcustomerop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListBeneficialOwnersForCustomerRequest$zodSchema,
};

export const tool$customersBeneficialOwnersList: ToolDefinition<typeof args> = {
  name: "customers-beneficial-owners-list",
  description: `List beneficial owners

Retrieve a list of beneficial owners that belong to a Customer`,
  scopes: ["read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await customersBeneficialOwnersList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
