/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersTransfersList } from "../../funcs/customersTransfersList.js";
import { ListCustomerTransfersRequest$zodSchema } from "../../models/listcustomertransfersop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListCustomerTransfersRequest$zodSchema,
};

export const tool$customersTransfersList: ToolDefinition<typeof args> = {
  name: "customers-transfers-list",
  description: `List and search transfers for a customer

List and search transfers for a customer`,
  scopes: ["read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await customersTransfersList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
