/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersExchangesList } from "../../funcs/customersExchangesList.js";
import { ListCustomerExchangesRequest$zodSchema } from "../../models/listcustomerexchangesop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListCustomerExchangesRequest$zodSchema,
};

export const tool$customersExchangesList: ToolDefinition<typeof args> = {
  name: "customers-exchanges-list",
  description: `List exchanges for a customer

Retrieve the list of exchanges associated with a Customer resource.`,
  scopes: ["read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await customersExchangesList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
