/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customers_update } from "../../funcs/customers_update.js";
import { UpdateRequest$zodSchema } from "../../models/operations/update.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateRequest$zodSchema,
};

export const tool$customers_update: ToolDefinition<typeof args> = {
  name: "customers-update",
  description: `Update a customer

Update Customer information, upgrade an unverified Customer to a verified Customer, suspend a Customer, deactivate a Customer, reactivate a Customer, and update a verified Customer's information to retry verification.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await customers_update(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
