/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customers_documents_create } from "../../funcs/customers_documents_create.js";
import { CreateCustomerDocumentRequest$zodSchema } from "../../models/operations/createcustomerdocument.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateCustomerDocumentRequest$zodSchema,
};

export const tool$customers_documents_create: ToolDefinition<typeof args> = {
  name: "customers-documents-create",
  description: `Create a document for customer

Create a document for customer`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await customers_documents_create(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
