/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersMassPaymentsList } from "../../funcs/customersMassPaymentsList.js";
import { ListCustomerMassPaymentsRequest$zodSchema } from "../../models/listcustomermasspaymentsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListCustomerMassPaymentsRequest$zodSchema,
};

export const tool$customersMassPaymentsList: ToolDefinition<typeof args> = {
  name: "customers-mass-payments-list",
  description: `List mass payments for customer

List mass payments for customer`,
  scopes: ["read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await customersMassPaymentsList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
