/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersGet } from "../../funcs/customersGet.js";
import { GetCustomerRequest$zodSchema } from "../../models/getcustomerop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetCustomerRequest$zodSchema,
};

export const tool$customersGet: ToolDefinition<typeof args> = {
  name: "customers-get",
  description: `Retrieve a customer

Retrieve identifying information for a specific customer. The returned data varies by customer type - verified customers include contact details, address information, and verification status, while unverified customers and receive-only users contain basic contact information only.`,
  scopes: ["read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await customersGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
