/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customers_beneficialOwners_list } from "../../funcs/customers_beneficialOwners_list.js";
import { ListBeneficialOwnersForCustomerRequest$zodSchema } from "../../models/operations/listbeneficialownersforcustomer.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListBeneficialOwnersForCustomerRequest$zodSchema,
};

export const tool$customers_beneficialOwners_list: ToolDefinition<typeof args> =
  {
    name: "customers-beneficial-owners-list",
    description: `List beneficial owners

Retrieve a list of beneficial owners that belong to a Customer`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await customers_beneficialOwners_list(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
