/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersMassPaymentsList } from "../../funcs/customersMassPaymentsList.js";
import { ListCustomerMassPaymentsRequest$zodSchema } from "../../models/listcustomermasspaymentsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListCustomerMassPaymentsRequest$zodSchema,
};

export const tool$customersMassPaymentsList: ToolDefinition<typeof args> = {
  name: "customers-mass-payments-list",
  description: `List mass payments for customer

Retrieve all previously created mass payments for a Verified Customer account with optional correlation ID filtering and pagination support. Mass payments are returned ordered by date created with most recent appearing first. Returns paginated results including mass payment status, metadata, source funding information, and item links. Supports standard pagination parameters and correlation ID search for enhanced traceability.`,
  scopes: ["read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await customersMassPaymentsList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
