/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { documentsGet } from "../../funcs/documentsGet.js";
import { RetrieveDocumentRequest$zodSchema } from "../../models/retrievedocumentop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: RetrieveDocumentRequest$zodSchema,
};

export const tool$documentsGet: ToolDefinition<typeof args> = {
  name: "documents-get",
  description: `Retrieve a document

Returns detailed information about a specific identity verification document, including its status, type, and verification results. Used to track document submission and verification progress during the business verification process.`,
  scopes: ["read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await documentsGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
