/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { documents_get } from "../../funcs/documents_get.js";
import { GetDocumentRequest$zodSchema } from "../../models/operations/getdocument.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetDocumentRequest$zodSchema,
};

export const tool$documents_get: ToolDefinition<typeof args> = {
  name: "documents-get",
  description: `Retrieve a document

Retrieve a document for a customer or beneficial owner`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await documents_get(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
