/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventsGet } from "../../funcs/eventsGet.js";
import { GetEventRequest$zodSchema } from "../../models/geteventop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetEventRequest$zodSchema,
};

export const tool$eventsGet: ToolDefinition<typeof args> = {
  name: "events-get",
  description: `Retrieve event

Returns detailed information for a specific event representing a state change that occurred on a resource in your Dwolla application. Includes the event topic, timestamp, resource links, and correlation ID if applicable.`,
  scopes: ["read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await eventsGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
