/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { events_list } from "../../funcs/events_list.js";
import { ListEventsRequest$zodSchema } from "../../models/operations/listevents.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListEventsRequest$zodSchema.optional(),
};

export const tool$events_list: ToolDefinition<typeof args> = {
  name: "events-list",
  description: `List events

List events`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await events_list(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
