/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { events_get } from "../../funcs/events_get.js";
import { GetEventRequest$zodSchema } from "../../models/operations/getevent.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetEventRequest$zodSchema,
};

export const tool$events_get: ToolDefinition<typeof args> = {
  name: "events-get",
  description: `Retrieve event

Retrieve event`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await events_get(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
