/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { exchanges_get } from "../../funcs/exchanges_get.js";
import { GetExchangeRequest$zodSchema } from "../../models/operations/getexchange.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetExchangeRequest$zodSchema,
};

export const tool$exchanges_get: ToolDefinition<typeof args> = {
  name: "exchanges-get",
  description: `Retrieve exchange resource

Retrieve exchange resource`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await exchanges_get(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
