/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { exchangePartners_list } from "../../funcs/exchangePartners_list.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$exchangePartners_list: ToolDefinition = {
  name: "exchange-partners-list",
  description: `List exchange partners

List exchange partners`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await exchangePartners_list(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
