/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { exchanges_createReAuth } from "../../funcs/exchanges_createReAuth.js";
import { CreateReAuthExchangeSessionRequest$zodSchema } from "../../models/operations/createreauthexchangesession.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateReAuthExchangeSessionRequest$zodSchema,
};

export const tool$exchanges_createReAuth: ToolDefinition<typeof args> = {
  name: "exchanges-create-re-auth",
  description: `Create re-authentication exchange session

Create a new re-authentication exchange session.

Request body requirements vary by exchange type:
- For Visa: Request body with redirect URL is required
- For Plaid Web: No request body is required
- For Plaid Mobile: Request body with redirect URL is required

The redirect URL will be validated against previously configured URLs stored in Dwolla.
After completing the re-authorization process, the user will be redirected back to your application using this URL.
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await exchanges_createReAuth(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
