/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { exchangesGet } from "../../funcs/exchangesGet.js";
import { GetExchangeRequest$zodSchema } from "../../models/getexchangeop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetExchangeRequest$zodSchema,
};

export const tool$exchangesGet: ToolDefinition<typeof args> = {
  name: "exchanges-get",
  description: `Retrieve exchange resource

Returns details for a specific exchange connection between Dwolla and an open banking partner for a customer's bank account. Includes exchange status, creation date, and links to the associated customer and exchange partner.`,
  scopes: ["read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await exchangesGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
