/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { fundingSources_createForCustomer } from "../../funcs/fundingSources_createForCustomer.js";
import { CreateCustomerFundingSourceRequest$zodSchema } from "../../models/operations/createcustomerfundingsource.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateCustomerFundingSourceRequest$zodSchema,
};

export const tool$fundingSources_createForCustomer: ToolDefinition<
  typeof args
> = {
  name: "funding-sources-create-for-customer",
  description: `Create customer funding source

Create a new funding source for a customer.
There are multiple methods available:
- Basic bank funding source (with routing/account numbers)
- Using an exchange
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await fundingSources_createForCustomer(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
