/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { fundingSources_getVanRouting } from "../../funcs/fundingSources_getVanRouting.js";
import { GetVanRoutingRequest$zodSchema } from "../../models/operations/getvanrouting.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetVanRoutingRequest$zodSchema,
};

export const tool$fundingSources_getVanRouting: ToolDefinition<typeof args> = {
  name: "funding-sources-get-van-routing",
  description: `Retrieve VAN account and routing numbers

Retrieve account and routing numbers for a VAN (Virtual Account Number)`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await fundingSources_getVanRouting(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
