/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { fundingSources_initiateOrVerifyMicroDeposits } from "../../funcs/fundingSources_initiateOrVerifyMicroDeposits.js";
import { InitiateOrVerifyMicroDepositsRequest$zodSchema } from "../../models/operations/initiateorverifymicrodeposits.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: InitiateOrVerifyMicroDepositsRequest$zodSchema,
};

export const tool$fundingSources_initiateOrVerifyMicroDeposits: ToolDefinition<
  typeof args
> = {
  name: "funding-sources-initiate-or-verify-micro-deposits",
  description: `Initiate or Verify micro-deposits

This endpoint handles two different actions:
1. Initiating micro-deposits: No request body is required
2. Verifying micro-deposits: Request body with micro-deposit amounts is required

The action is determined by the presence of a request body:
- If no request body is provided, the endpoint will initiate micro-deposits
- If a request body with micro-deposit amounts is provided, the endpoint will verify the micro-deposits
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] =
      await fundingSources_initiateOrVerifyMicroDeposits(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
