/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { fundingSourcesGetVanRouting } from "../../funcs/fundingSourcesGetVanRouting.js";
import { GetVanRoutingRequest$zodSchema } from "../../models/getvanroutingop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetVanRoutingRequest$zodSchema,
};

export const tool$fundingSourcesGetVanRouting: ToolDefinition<typeof args> = {
  name: "funding-sources-get-van-routing",
  description: `Retrieve VAN account and routing numbers

Returns the unique account and routing numbers for a Virtual Account Number (VAN) funding source. These numbers can be used by external systems to initiate ACH transactions that pull funds from or push funds to the associated Dwolla balance.`,
  scopes: ["read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await fundingSourcesGetVanRouting(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
