/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { labelLedgerEntriesGet } from "../../funcs/labelLedgerEntriesGet.js";
import { GetLabelLedgerEntryRequest$zodSchema } from "../../models/getlabelledgerentryop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetLabelLedgerEntryRequest$zodSchema,
};

export const tool$labelLedgerEntriesGet: ToolDefinition<typeof args> = {
  name: "label-ledger-entries-get",
  description: `Retrieve a label ledger entry

Returns detailed information for a specific ledger entry on a Label, including its amount, currency, and creation timestamp.`,
  scopes: ["read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await labelLedgerEntriesGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
