/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { labelsGet } from "../../funcs/labelsGet.js";
import { GetLabelRequest$zodSchema } from "../../models/getlabelop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetLabelRequest$zodSchema,
};

export const tool$labelsGet: ToolDefinition<typeof args> = {
  name: "labels-get",
  description: `Retrieve a label

Retrieve details for a specific Label used to categorize and track funds within your account. Returns Label information including unique identifier, current amount with currency, and creation timestamp.`,
  scopes: ["read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await labelsGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
