/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { labelsGetReallocation } from "../../funcs/labelsGetReallocation.js";
import { RetrieveLabelReallocationRequest$zodSchema } from "../../models/retrievelabelreallocationop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: RetrieveLabelReallocationRequest$zodSchema,
};

export const tool$labelsGetReallocation: ToolDefinition<typeof args> = {
  name: "labels-get-reallocation",
  description: `Retrieve a label reallocation

Retrieve a label reallocation`,
  scopes: ["read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await labelsGetReallocation(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
