/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { labels_getLedgerEntry } from "../../funcs/labels_getLedgerEntry.js";
import { GetLabelLedgerEntryRequest$zodSchema } from "../../models/operations/getlabelledgerentry.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetLabelLedgerEntryRequest$zodSchema,
};

export const tool$labels_getLedgerEntry: ToolDefinition<typeof args> = {
  name: "labels-get-ledger-entry",
  description: `Retrieve a label ledger entry

Retrieve a label ledger entry`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await labels_getLedgerEntry(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
