/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { labels_createReallocation } from "../../funcs/labels_createReallocation.js";
import { CreateLabelReallocationRequest$zodSchema } from "../../models/operations/createlabelreallocation.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateLabelReallocationRequest$zodSchema,
};

export const tool$labels_createReallocation: ToolDefinition<typeof args> = {
  name: "labels-create-reallocation",
  description: `Create a label reallocation

Create a label reallocation`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await labels_createReallocation(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
