/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { labels_get } from "../../funcs/labels_get.js";
import { GetLabelRequest$zodSchema } from "../../models/operations/getlabel.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetLabelRequest$zodSchema,
};

export const tool$labels_get: ToolDefinition<typeof args> = {
  name: "labels-get",
  description: `Retrieve a label

Retrieve a label`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await labels_get(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
