/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { labelsListForCustomer } from "../../funcs/labelsListForCustomer.js";
import { ListCustomerLabelsRequest$zodSchema } from "../../models/listcustomerlabelsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListCustomerLabelsRequest$zodSchema,
};

export const tool$labelsListForCustomer: ToolDefinition<typeof args> = {
  name: "labels-list-for-customer",
  description: `List labels for a customer

List labels for a customer`,
  scopes: ["read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await labelsListForCustomer(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
