/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { massPayments_update } from "../../funcs/massPayments_update.js";
import { UpdateMassPaymentRequest$zodSchema } from "../../models/operations/updatemasspayment.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateMassPaymentRequest$zodSchema,
};

export const tool$massPayments_update: ToolDefinition<typeof args> = {
  name: "mass-payments-update",
  description: `Update a mass payment

This section covers how to update a mass payment's status to \`pending\` which triggers processing on a created and deferred mass payment, or \`cancelled\` which cancels a created and deferred mass payment.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await massPayments_update(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
