/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { massPayments_create } from "../../funcs/massPayments_create.js";
import { InitiateMassPaymentRequest$zodSchema } from "../../models/operations/initiatemasspayment.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: InitiateMassPaymentRequest$zodSchema,
};

export const tool$massPayments_create: ToolDefinition<typeof args> = {
  name: "mass-payments-create",
  description: `Initiate a mass payment

Initiate a mass payment`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await massPayments_create(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
