/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { root_get } from "../../funcs/root_get.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$root_get: ToolDefinition = {
  name: "root-get",
  description: `root

The entry point that clients can use to discover and explore the entire API.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await root_get(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
