/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { transfersFailureGet } from "../../funcs/transfersFailureGet.js";
import { GetTransferFailureReasonRequest$zodSchema } from "../../models/gettransferfailurereasonop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetTransferFailureReasonRequest$zodSchema,
};

export const tool$transfersFailureGet: ToolDefinition<typeof args> = {
  name: "transfers-failure-get",
  description: `Retrieve a transfer failure reason

Retrieve detailed failure information for a failed bank or VAN transfer including the ACH return code, description, and explanation. Returns failure details with links to the failed funding source and associated Customer for comprehensive error analysis. Available only for transfers with failure status and accessed through the failure link from transfer retrieval. Critical for troubleshooting payment failures and understanding ACH return reasons.`,
  scopes: ["read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await transfersFailureGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
