/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { transfers_listFees } from "../../funcs/transfers_listFees.js";
import { ListTransferFeesRequest$zodSchema } from "../../models/operations/listtransferfees.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListTransferFeesRequest$zodSchema,
};

export const tool$transfers_listFees: ToolDefinition<typeof args> = {
  name: "transfers-list-fees",
  description: `List fees for a transfer

List fees for a transfer`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await transfers_listFees(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
