/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { transfers_getFailureReason } from "../../funcs/transfers_getFailureReason.js";
import { GetTransferFailureReasonRequest$zodSchema } from "../../models/operations/gettransferfailurereason.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetTransferFailureReasonRequest$zodSchema,
};

export const tool$transfers_getFailureReason: ToolDefinition<typeof args> = {
  name: "transfers-get-failure-reason",
  description: `Retrieve a transfer failure reason

Retrieve a transfer failure reason`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await transfers_getFailureReason(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
