/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { transfers_create } from "../../funcs/transfers_create.js";
import { InitiateTransferRequest$zodSchema } from "../../models/operations/initiatetransfer.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: InitiateTransferRequest$zodSchema,
};

export const tool$transfers_create: ToolDefinition<typeof args> = {
  name: "transfers-create",
  description: `Initiate a transfer

Initiate a transfer`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await transfers_create(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
