/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhooks_retry } from "../../funcs/webhooks_retry.js";
import { RetryWebhookRequest$zodSchema } from "../../models/operations/retrywebhook.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: RetryWebhookRequest$zodSchema,
};

export const tool$webhooks_retry: ToolDefinition<typeof args> = {
  name: "webhooks-retry",
  description: `Retry a webhook

Retry a webhook`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await webhooks_retry(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
