/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhooksGet } from "../../funcs/webhooksGet.js";
import { GetWebhookRequest$zodSchema } from "../../models/getwebhookop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetWebhookRequest$zodSchema,
};

export const tool$webhooksGet: ToolDefinition<typeof args> = {
  name: "webhooks-get",
  description: `Retrieve a webhook

Retrieve detailed information for a specific webhook by its unique identifier including delivery attempts and response data. Returns webhook details with topic, account information, delivery attempts containing request/response history, and links to subscription and retry resources. Essential for debugging webhook delivery issues, analyzing response data, and monitoring notification processing status.`,
  scopes: ["read"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await webhooksGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
