/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhookSubscriptions_list } from "../../funcs/webhookSubscriptions_list.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$webhookSubscriptions_list: ToolDefinition = {
  name: "webhook-subscriptions-list",
  description: `List webhook subscriptions

List webhook subscriptions`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await webhookSubscriptions_list(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
