/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhookSubscriptions_delete } from "../../funcs/webhookSubscriptions_delete.js";
import { DeleteRequest$zodSchema } from "../../models/operations/delete.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteRequest$zodSchema,
};

export const tool$webhookSubscriptions_delete: ToolDefinition<typeof args> = {
  name: "webhook-subscriptions-delete",
  description: `Delete a webhook subscription

Delete a webhook subscription`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await webhookSubscriptions_delete(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
