/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhooks_listRetries } from "../../funcs/webhooks_listRetries.js";
import { ListWebhookRetriesRequest$zodSchema } from "../../models/operations/listwebhookretries.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListWebhookRetriesRequest$zodSchema,
};

export const tool$webhooks_listRetries: ToolDefinition<typeof args> = {
  name: "webhooks-list-retries",
  description: `List retries for a webhook

List retries for a webhook`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await webhooks_listRetries(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
