/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhookSubscriptions_listWebhooks } from "../../funcs/webhookSubscriptions_listWebhooks.js";
import { ListWebhooksRequest$zodSchema } from "../../models/operations/listwebhooks.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListWebhooksRequest$zodSchema,
};

export const tool$webhookSubscriptions_listWebhooks: ToolDefinition<
  typeof args
> = {
  name: "webhook-subscriptions-list-webhooks",
  description: `List webhooks for a webhook subscription

List webhooks for a webhook subscription`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await webhookSubscriptions_listWebhooks(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
