/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { DwollaMcpCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import { createRegisterPrompt } from "./prompts.js";
import {
  createRegisterResource,
  createRegisterResourceTemplate,
} from "./resources.js";
import { MCPScope } from "./scopes.js";
import { createRegisterTool } from "./tools.js";
import { tool$accounts_exchanges_create } from "./tools/accounts_exchanges_create.js";
import { tool$accounts_exchanges_list } from "./tools/accounts_exchanges_list.js";
import { tool$accounts_fundingSources_create } from "./tools/accounts_fundingSources_create.js";
import { tool$accounts_fundingSources_list } from "./tools/accounts_fundingSources_list.js";
import { tool$accounts_get } from "./tools/accounts_get.js";
import { tool$accounts_massPayments_list } from "./tools/accounts_massPayments_list.js";
import { tool$accounts_transfers_list } from "./tools/accounts_transfers_list.js";
import { tool$beneficialOwners_certifyOwnership } from "./tools/beneficialOwners_certifyOwnership.js";
import { tool$beneficialOwners_delete } from "./tools/beneficialOwners_delete.js";
import { tool$beneficialOwners_documents_create } from "./tools/beneficialOwners_documents_create.js";
import { tool$beneficialOwners_documents_list } from "./tools/beneficialOwners_documents_list.js";
import { tool$beneficialOwners_get } from "./tools/beneficialOwners_get.js";
import { tool$beneficialOwners_getOwnershipStatus } from "./tools/beneficialOwners_getOwnershipStatus.js";
import { tool$beneficialOwners_update } from "./tools/beneficialOwners_update.js";
import { tool$businessClassifications_get } from "./tools/businessClassifications_get.js";
import { tool$businessClassifications_list } from "./tools/businessClassifications_list.js";
import { tool$clientTokens_create } from "./tools/clientTokens_create.js";
import { tool$customers_beneficialOwners_create } from "./tools/customers_beneficialOwners_create.js";
import { tool$customers_beneficialOwners_list } from "./tools/customers_beneficialOwners_list.js";
import { tool$customers_create } from "./tools/customers_create.js";
import { tool$customers_documents_create } from "./tools/customers_documents_create.js";
import { tool$customers_documents_list } from "./tools/customers_documents_list.js";
import { tool$customers_exchanges_create } from "./tools/customers_exchanges_create.js";
import { tool$customers_exchanges_list } from "./tools/customers_exchanges_list.js";
import { tool$customers_fundingSources_list } from "./tools/customers_fundingSources_list.js";
import { tool$customers_get } from "./tools/customers_get.js";
import { tool$customers_list } from "./tools/customers_list.js";
import { tool$customers_listAvailableConnections } from "./tools/customers_listAvailableConnections.js";
import { tool$customers_update } from "./tools/customers_update.js";
import { tool$documents_get } from "./tools/documents_get.js";
import { tool$events_get } from "./tools/events_get.js";
import { tool$events_list } from "./tools/events_list.js";
import { tool$exchangePartners_get } from "./tools/exchangePartners_get.js";
import { tool$exchangePartners_list } from "./tools/exchangePartners_list.js";
import { tool$exchanges_createReAuth } from "./tools/exchanges_createReAuth.js";
import { tool$exchanges_get } from "./tools/exchanges_get.js";
import { tool$exchangeSessions_create } from "./tools/exchangeSessions_create.js";
import { tool$exchangeSessions_get } from "./tools/exchangeSessions_get.js";
import { tool$fundingSources_createForCustomer } from "./tools/fundingSources_createForCustomer.js";
import { tool$fundingSources_get } from "./tools/fundingSources_get.js";
import { tool$fundingSources_getBalance } from "./tools/fundingSources_getBalance.js";
import { tool$fundingSources_getMicroDeposits } from "./tools/fundingSources_getMicroDeposits.js";
import { tool$fundingSources_getVanRouting } from "./tools/fundingSources_getVanRouting.js";
import { tool$fundingSources_initiateOrVerifyMicroDeposits } from "./tools/fundingSources_initiateOrVerifyMicroDeposits.js";
import { tool$fundingSources_updateOrRemove } from "./tools/fundingSources_updateOrRemove.js";
import { tool$kba_getQuestions } from "./tools/kba_getQuestions.js";
import { tool$kba_initiate } from "./tools/kba_initiate.js";
import { tool$kba_verify } from "./tools/kba_verify.js";
import { tool$labels_createForCustomer } from "./tools/labels_createForCustomer.js";
import { tool$labels_createLedgerEntry } from "./tools/labels_createLedgerEntry.js";
import { tool$labels_createReallocation } from "./tools/labels_createReallocation.js";
import { tool$labels_get } from "./tools/labels_get.js";
import { tool$labels_getLedgerEntry } from "./tools/labels_getLedgerEntry.js";
import { tool$labels_getReallocation } from "./tools/labels_getReallocation.js";
import { tool$labels_listForCustomer } from "./tools/labels_listForCustomer.js";
import { tool$labels_listLedgerEntries } from "./tools/labels_listLedgerEntries.js";
import { tool$labels_remove } from "./tools/labels_remove.js";
import { tool$massPayments_create } from "./tools/massPayments_create.js";
import { tool$massPayments_get } from "./tools/massPayments_get.js";
import { tool$massPayments_getItem } from "./tools/massPayments_getItem.js";
import { tool$massPayments_listForCustomer } from "./tools/massPayments_listForCustomer.js";
import { tool$massPayments_listItems } from "./tools/massPayments_listItems.js";
import { tool$massPayments_update } from "./tools/massPayments_update.js";
import { tool$root_get } from "./tools/root_get.js";
import { tool$tokens_createApplicationAccessToken } from "./tools/tokens_createApplicationAccessToken.js";
import { tool$transfers_cancel } from "./tools/transfers_cancel.js";
import { tool$transfers_create } from "./tools/transfers_create.js";
import { tool$transfers_createOnDemandAuthorization } from "./tools/transfers_createOnDemandAuthorization.js";
import { tool$transfers_get } from "./tools/transfers_get.js";
import { tool$transfers_getFailureReason } from "./tools/transfers_getFailureReason.js";
import { tool$transfers_listFees } from "./tools/transfers_listFees.js";
import { tool$transfers_listForCustomer } from "./tools/transfers_listForCustomer.js";
import { tool$webhooks_get } from "./tools/webhooks_get.js";
import { tool$webhooks_listRetries } from "./tools/webhooks_listRetries.js";
import { tool$webhooks_retry } from "./tools/webhooks_retry.js";
import { tool$webhookSubscriptions_create } from "./tools/webhookSubscriptions_create.js";
import { tool$webhookSubscriptions_delete } from "./tools/webhookSubscriptions_delete.js";
import { tool$webhookSubscriptions_get } from "./tools/webhookSubscriptions_get.js";
import { tool$webhookSubscriptions_list } from "./tools/webhookSubscriptions_list.js";
import { tool$webhookSubscriptions_listWebhooks } from "./tools/webhookSubscriptions_listWebhooks.js";
import { tool$webhookSubscriptions_update } from "./tools/webhookSubscriptions_update.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  allowedTools?: string[] | undefined;
  scopes?: MCPScope[] | undefined;
  serverURL?: string | undefined;
  security?: SDKOptions["security"] | undefined;
  serverIdx?: SDKOptions["serverIdx"] | undefined;
}) {
  const server = new McpServer({
    name: "DwollaMcp",
    version: "0.0.3",
  });

  const client = new DwollaMcpCore({
    security: deps.security,
    serverURL: deps.serverURL,
    serverIdx: deps.serverIdx,
  });

  const scopes = new Set(deps.scopes);

  const allowedTools = deps.allowedTools && new Set(deps.allowedTools);
  const tool = createRegisterTool(
    deps.logger,
    server,
    client,
    scopes,
    allowedTools,
  );
  const resource = createRegisterResource(deps.logger, server, client, scopes);
  const resourceTemplate = createRegisterResourceTemplate(
    deps.logger,
    server,
    client,
    scopes,
  );
  const prompt = createRegisterPrompt(deps.logger, server, client, scopes);
  const register = { tool, resource, resourceTemplate, prompt };
  void register; // suppress unused warnings

  tool(tool$tokens_createApplicationAccessToken);
  tool(tool$root_get);
  tool(tool$accounts_get);
  tool(tool$accounts_fundingSources_create);
  tool(tool$accounts_fundingSources_list);
  tool(tool$accounts_transfers_list);
  tool(tool$accounts_massPayments_list);
  tool(tool$customers_list);
  tool(tool$customers_create);
  tool(tool$customers_get);
  tool(tool$customers_update);
  tool(tool$customers_listAvailableConnections);
  tool(tool$businessClassifications_list);
  tool(tool$businessClassifications_get);
  tool(tool$customers_beneficialOwners_list);
  tool(tool$customers_beneficialOwners_create);
  tool(tool$beneficialOwners_get);
  tool(tool$beneficialOwners_update);
  tool(tool$beneficialOwners_delete);
  tool(tool$beneficialOwners_getOwnershipStatus);
  tool(tool$beneficialOwners_certifyOwnership);
  tool(tool$customers_documents_list);
  tool(tool$customers_documents_create);
  tool(tool$beneficialOwners_documents_list);
  tool(tool$beneficialOwners_documents_create);
  tool(tool$documents_get);
  tool(tool$kba_initiate);
  tool(tool$kba_getQuestions);
  tool(tool$kba_verify);
  tool(tool$customers_fundingSources_list);
  tool(tool$fundingSources_createForCustomer);
  tool(tool$fundingSources_get);
  tool(tool$fundingSources_updateOrRemove);
  tool(tool$fundingSources_getMicroDeposits);
  tool(tool$fundingSources_initiateOrVerifyMicroDeposits);
  tool(tool$fundingSources_getBalance);
  tool(tool$fundingSources_getVanRouting);
  tool(tool$transfers_create);
  tool(tool$transfers_get);
  tool(tool$transfers_cancel);
  tool(tool$transfers_listForCustomer);
  tool(tool$transfers_listFees);
  tool(tool$transfers_getFailureReason);
  tool(tool$transfers_createOnDemandAuthorization);
  tool(tool$massPayments_create);
  tool(tool$massPayments_get);
  tool(tool$massPayments_update);
  tool(tool$massPayments_listItems);
  tool(tool$massPayments_getItem);
  tool(tool$massPayments_listForCustomer);
  tool(tool$labels_get);
  tool(tool$labels_remove);
  tool(tool$labels_listForCustomer);
  tool(tool$labels_createForCustomer);
  tool(tool$labels_listLedgerEntries);
  tool(tool$labels_createLedgerEntry);
  tool(tool$labels_getLedgerEntry);
  tool(tool$labels_createReallocation);
  tool(tool$labels_getReallocation);
  tool(tool$events_list);
  tool(tool$events_get);
  tool(tool$webhookSubscriptions_list);
  tool(tool$webhookSubscriptions_create);
  tool(tool$webhookSubscriptions_get);
  tool(tool$webhookSubscriptions_update);
  tool(tool$webhookSubscriptions_delete);
  tool(tool$webhookSubscriptions_listWebhooks);
  tool(tool$webhooks_get);
  tool(tool$webhooks_listRetries);
  tool(tool$webhooks_retry);
  tool(tool$exchangePartners_list);
  tool(tool$exchangePartners_get);
  tool(tool$accounts_exchanges_list);
  tool(tool$accounts_exchanges_create);
  tool(tool$exchanges_get);
  tool(tool$exchanges_createReAuth);
  tool(tool$customers_exchanges_list);
  tool(tool$customers_exchanges_create);
  tool(tool$exchangeSessions_create);
  tool(tool$exchangeSessions_get);
  tool(tool$clientTokens_create);

  return server;
}
