/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { DwollaMcpCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import { createRegisterPrompt } from "./prompts.js";
import {
  createRegisterResource,
  createRegisterResourceTemplate,
} from "./resources.js";
import { MCPScope } from "./scopes.js";
import { createRegisterTool, registerDynamicTools } from "./tools.js";
import { tool$accountsExchangesList } from "./tools/accountsExchangesList.js";
import { tool$accountsFundingSourcesList } from "./tools/accountsFundingSourcesList.js";
import { tool$accountsGet } from "./tools/accountsGet.js";
import { tool$accountsMassPaymentsList } from "./tools/accountsMassPaymentsList.js";
import { tool$accountsTransfersList } from "./tools/accountsTransfersList.js";
import { tool$beneficialOwnersDocumentsList } from "./tools/beneficialOwnersDocumentsList.js";
import { tool$businessClassificationsList } from "./tools/businessClassificationsList.js";
import { tool$customersBeneficialOwnershipGet } from "./tools/customersBeneficialOwnershipGet.js";
import { tool$customersBeneficialOwnersList } from "./tools/customersBeneficialOwnersList.js";
import { tool$customersDocumentsList } from "./tools/customersDocumentsList.js";
import { tool$customersExchangesList } from "./tools/customersExchangesList.js";
import { tool$customersFundingSourcesList } from "./tools/customersFundingSourcesList.js";
import { tool$customersLabelsList } from "./tools/customersLabelsList.js";
import { tool$customersList } from "./tools/customersList.js";
import { tool$customersListAvailableConnections } from "./tools/customersListAvailableConnections.js";
import { tool$customersMassPaymentsList } from "./tools/customersMassPaymentsList.js";
import { tool$customersTransfersList } from "./tools/customersTransfersList.js";
import { tool$eventsList } from "./tools/eventsList.js";
import { tool$exchangePartnersList } from "./tools/exchangePartnersList.js";
import { tool$fundingSourcesBalanceGet } from "./tools/fundingSourcesBalanceGet.js";
import { tool$fundingSourcesGet } from "./tools/fundingSourcesGet.js";
import { tool$fundingSourcesMicroDepositsGetMicroDeposits } from "./tools/fundingSourcesMicroDepositsGetMicroDeposits.js";
import { tool$massPaymentsItemsList } from "./tools/massPaymentsItemsList.js";
import { tool$transfersFailureGet } from "./tools/transfersFailureGet.js";
import { tool$transfersFeesList } from "./tools/transfersFeesList.js";
import { tool$webhookSubscriptionsList } from "./tools/webhookSubscriptionsList.js";
import { tool$webhookSubscriptionsWebhooksList } from "./tools/webhookSubscriptionsWebhooksList.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  allowedTools?: string[] | undefined;
  dynamic?: boolean | undefined;
  scopes?: MCPScope[] | undefined;
  getSDK?: () => DwollaMcpCore;
  serverURL?: string | undefined;
  security?: SDKOptions["security"] | undefined;
  server?: SDKOptions["server"] | undefined;
}) {
  const server = new McpServer({
    name: "DwollaMcp",
    version: "1.1.1",
  });

  const getClient = deps.getSDK || (() =>
    new DwollaMcpCore({
      security: deps.security,
      serverURL: deps.serverURL,
      server: deps.server,
      debugLogger: deps.logger.level === "debug"
        ? {
          log: (...args) => console.log(...args),
          group: (...args) => console.group(...args),
          groupEnd: (...args) => console.groupEnd(...args),
        }
        : undefined,
    }));

  const scopes = new Set(deps.scopes);

  const allowedTools = deps.allowedTools && new Set(deps.allowedTools);
  const [tool, tools, toolMap] = createRegisterTool(
    deps.logger,
    server,
    getClient,
    scopes,
    allowedTools,
    deps.dynamic,
  );
  const resource = createRegisterResource(
    deps.logger,
    server,
    getClient,
    scopes,
  );
  const resourceTemplate = createRegisterResourceTemplate(
    deps.logger,
    server,
    getClient,
    scopes,
  );
  const prompt = createRegisterPrompt(deps.logger, server, getClient, scopes);
  const register = { tool, resource, resourceTemplate, prompt };
  void register; // suppress unused warnings

  tool(tool$accountsGet);
  tool(tool$accountsFundingSourcesList);
  tool(tool$accountsTransfersList);
  tool(tool$accountsMassPaymentsList);
  tool(tool$customersList);
  tool(tool$customersListAvailableConnections);
  tool(tool$businessClassificationsList);
  tool(tool$customersBeneficialOwnersList);
  tool(tool$customersBeneficialOwnershipGet);
  tool(tool$customersDocumentsList);
  tool(tool$beneficialOwnersDocumentsList);
  tool(tool$customersFundingSourcesList);
  tool(tool$fundingSourcesGet);
  tool(tool$fundingSourcesMicroDepositsGetMicroDeposits);
  tool(tool$fundingSourcesBalanceGet);
  tool(tool$customersTransfersList);
  tool(tool$transfersFeesList);
  tool(tool$transfersFailureGet);
  tool(tool$massPaymentsItemsList);
  tool(tool$customersMassPaymentsList);
  tool(tool$customersLabelsList);
  tool(tool$eventsList);
  tool(tool$webhookSubscriptionsList);
  tool(tool$webhookSubscriptionsWebhooksList);
  tool(tool$exchangePartnersList);
  tool(tool$accountsExchangesList);
  tool(tool$customersExchangesList);

  if (deps.dynamic) {
    registerDynamicTools(deps.logger, server, getClient, toolMap, scopes);
  }

  return { server, tools };
}
