workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Dwolla API:
        inputs:
            - location: https://raw.githubusercontent.com/Dwolla/dwolla-openapi/refs/heads/main/openapi.yml
        overlays:
            - location: ./.speakeasy/mcp-overlay.yaml
        output: ./generated/openapi/openapi-mcp.yaml
        registry:
            location: registry.speakeasyapi.dev/dwolla-vc3/dwolla/dwolla-api
targets:
    dwolla-mcp:
        target: mcp-typescript
        source: Dwolla API
        publish:
            npm:
                token: $npm_token
