/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  BadRequestError,
  BadRequestError$zodSchema,
} from "../components/badrequesterror.js";
import {
  ForbiddenError,
  ForbiddenError$zodSchema,
} from "../components/forbiddenerror.js";

export type CreateClientTokenCustomer = { href: string };

export const CreateClientTokenCustomer$zodSchema: z.ZodType<
  CreateClientTokenCustomer,
  z.ZodTypeDef,
  unknown
> = z.object({
  href: z.string(),
});

export type CreateClientTokenLinks = { customer: CreateClientTokenCustomer };

export const CreateClientTokenLinks$zodSchema: z.ZodType<
  CreateClientTokenLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  customer: z.lazy(() => CreateClientTokenCustomer$zodSchema),
});

export type CreateClientTokenRequest = {
  action: string;
  _links: CreateClientTokenLinks;
};

export const CreateClientTokenRequest$zodSchema: z.ZodType<
  CreateClientTokenRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  _links: z.lazy(() => CreateClientTokenLinks$zodSchema),
  action: z.string(),
});

/**
 * Client token created successfully
 */
export type CreateClientTokenResponseBody = { token: string };

export const CreateClientTokenResponseBody$zodSchema: z.ZodType<
  CreateClientTokenResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  token: z.string(),
}).describe("Client token created successfully");

export type CreateClientTokenResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: CreateClientTokenResponseBody | undefined;
  BadRequestError?: BadRequestError | undefined;
  ForbiddenError?: ForbiddenError | undefined;
};

export const CreateClientTokenResponse$zodSchema: z.ZodType<
  CreateClientTokenResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  BadRequestError: BadRequestError$zodSchema.optional(),
  ContentType: z.string(),
  ForbiddenError: ForbiddenError$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  object: z.lazy(() => CreateClientTokenResponseBody$zodSchema).optional(),
});
