/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteBeneficialOwnerRequest = { id: string };

export const DeleteBeneficialOwnerRequest$zodSchema: z.ZodType<
  DeleteBeneficialOwnerRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().describe("Beneficial owner unique identifier"),
});

/**
 * not found
 */
export type DeleteBeneficialOwnerNotFoundResponseBody = {
  code?: string | undefined;
  message?: string | undefined;
};

export const DeleteBeneficialOwnerNotFoundResponseBody$zodSchema: z.ZodType<
  DeleteBeneficialOwnerNotFoundResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string().optional(),
  message: z.string().optional(),
}).describe("not found");

/**
 * successful operation
 */
export type DeleteBeneficialOwnerResponseBody = {};

export const DeleteBeneficialOwnerResponseBody$zodSchema: z.ZodType<
  DeleteBeneficialOwnerResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({}).describe("successful operation");

export type DeleteBeneficialOwnerResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredApplicationVndDwollaV1HalPlusJsonObject?:
    | DeleteBeneficialOwnerResponseBody
    | undefined;
  fourHundredAndFourApplicationVndDwollaV1HalPlusJsonObject?:
    | DeleteBeneficialOwnerNotFoundResponseBody
    | undefined;
};

export const DeleteBeneficialOwnerResponse$zodSchema: z.ZodType<
  DeleteBeneficialOwnerResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  fourHundredAndFourApplicationVndDwollaV1HalPlusJsonObject: z.lazy(() =>
    DeleteBeneficialOwnerNotFoundResponseBody$zodSchema
  ).optional(),
  twoHundredApplicationVndDwollaV1HalPlusJsonObject: z.lazy(() =>
    DeleteBeneficialOwnerResponseBody$zodSchema
  ).optional(),
});
