/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  NotFoundError,
  NotFoundError$zodSchema,
} from "../components/notfounderror.js";
import {
  WebhookSubscription,
  WebhookSubscription$zodSchema,
} from "../components/webhooksubscription.js";

export type GetWebhookSubscriptionRequest = { id: string };

export const GetWebhookSubscriptionRequest$zodSchema: z.ZodType<
  GetWebhookSubscriptionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().describe("Webhook subscription unique identifier"),
});

export type GetWebhookSubscriptionResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  WebhookSubscription?: WebhookSubscription | undefined;
  NotFoundError?: NotFoundError | undefined;
};

export const GetWebhookSubscriptionResponse$zodSchema: z.ZodType<
  GetWebhookSubscriptionResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  NotFoundError: NotFoundError$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  WebhookSubscription: WebhookSubscription$zodSchema.optional(),
});
