/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  MassPayments,
  MassPayments$zodSchema,
} from "../components/masspayments.js";

export type ListMassPaymentsRequest = {
  id: string;
  limit?: number | undefined;
  offset?: number | undefined;
  correlationId?: string | undefined;
};

export const ListMassPaymentsRequest$zodSchema: z.ZodType<
  ListMassPaymentsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  correlationId: z.string().describe("Correlation ID to search by.").optional(),
  id: z.string().describe("Account ID"),
  limit: z.number().int().default(25).describe("How many results to return."),
  offset: z.number().int().default(0).describe("How many results to skip."),
});

/**
 * not found
 */
export type ListMassPaymentsNotFoundResponseBody = {
  code?: string | undefined;
  message?: string | undefined;
};

export const ListMassPaymentsNotFoundResponseBody$zodSchema: z.ZodType<
  ListMassPaymentsNotFoundResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string().optional(),
  message: z.string().optional(),
}).describe("not found");

/**
 * forbidden
 */
export type ListMassPaymentsForbiddenResponseBody = {
  code?: string | undefined;
  message?: string | undefined;
};

export const ListMassPaymentsForbiddenResponseBody$zodSchema: z.ZodType<
  ListMassPaymentsForbiddenResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string().optional(),
  message: z.string().optional(),
}).describe("forbidden");

export type ListMassPaymentsResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  MassPayments?: MassPayments | undefined;
  fourHundredAndThreeApplicationVndDwollaV1HalPlusJsonObject?:
    | ListMassPaymentsForbiddenResponseBody
    | undefined;
  fourHundredAndFourApplicationVndDwollaV1HalPlusJsonObject?:
    | ListMassPaymentsNotFoundResponseBody
    | undefined;
};

export const ListMassPaymentsResponse$zodSchema: z.ZodType<
  ListMassPaymentsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  MassPayments: MassPayments$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  fourHundredAndFourApplicationVndDwollaV1HalPlusJsonObject: z.lazy(() =>
    ListMassPaymentsNotFoundResponseBody$zodSchema
  ).optional(),
  fourHundredAndThreeApplicationVndDwollaV1HalPlusJsonObject: z.lazy(() =>
    ListMassPaymentsForbiddenResponseBody$zodSchema
  ).optional(),
});
