/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  BadRequestError,
  BadRequestError$zodSchema,
} from "../components/badrequesterror.js";
import {
  MassPayment,
  MassPayment$zodSchema,
} from "../components/masspayment.js";

/**
 * Parameters for updating a mass payment
 */
export type UpdateMassPaymentRequestBody = { status: string };

export const UpdateMassPaymentRequestBody$zodSchema: z.ZodType<
  UpdateMassPaymentRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.string(),
}).describe("Parameters for updating a mass payment");

export type UpdateMassPaymentRequest = {
  id: string;
  RequestBody: UpdateMassPaymentRequestBody;
};

export const UpdateMassPaymentRequest$zodSchema: z.ZodType<
  UpdateMassPaymentRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  RequestBody: z.lazy(() => UpdateMassPaymentRequestBody$zodSchema),
  id: z.string().describe("ID of mass payment to update"),
});

/**
 * Not Found
 */
export type UpdateMassPaymentNotFoundResponseBody = {
  code?: string | undefined;
  message?: string | undefined;
};

export const UpdateMassPaymentNotFoundResponseBody$zodSchema: z.ZodType<
  UpdateMassPaymentNotFoundResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string().optional(),
  message: z.string().optional(),
}).describe("Not Found");

/**
 * Forbidden
 */
export type UpdateMassPaymentForbiddenResponseBody = {
  code?: string | undefined;
  message?: string | undefined;
};

export const UpdateMassPaymentForbiddenResponseBody$zodSchema: z.ZodType<
  UpdateMassPaymentForbiddenResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string().optional(),
  message: z.string().optional(),
}).describe("Forbidden");

export type UpdateMassPaymentResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  MassPayment?: MassPayment | undefined;
  BadRequestError?: BadRequestError | undefined;
  fourHundredAndThreeApplicationVndDwollaV1HalPlusJsonObject?:
    | UpdateMassPaymentForbiddenResponseBody
    | undefined;
  fourHundredAndFourApplicationVndDwollaV1HalPlusJsonObject?:
    | UpdateMassPaymentNotFoundResponseBody
    | undefined;
};

export const UpdateMassPaymentResponse$zodSchema: z.ZodType<
  UpdateMassPaymentResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  BadRequestError: BadRequestError$zodSchema.optional(),
  ContentType: z.string(),
  MassPayment: MassPayment$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  fourHundredAndFourApplicationVndDwollaV1HalPlusJsonObject: z.lazy(() =>
    UpdateMassPaymentNotFoundResponseBody$zodSchema
  ).optional(),
  fourHundredAndThreeApplicationVndDwollaV1HalPlusJsonObject: z.lazy(() =>
    UpdateMassPaymentForbiddenResponseBody$zodSchema
  ).optional(),
});
