/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Address = {
  address1: string;
  address2?: string | undefined;
  city: string;
  postalCode: string;
  state: string;
};

export const Address$zodSchema: z.ZodType<Address, z.ZodTypeDef, unknown> = z
  .object({
    address1: z.string(),
    address2: z.string().optional(),
    city: z.string(),
    postalCode: z.string(),
    state: z.string(),
  });
