/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { HalLink, HalLink$zodSchema } from "./hallink.js";

/**
 * Request body model for a Beneficial Owner
 */
export type BeneficialOwner = {
  _links?: { [k: string]: HalLink } | undefined;
  id?: string | undefined;
  verificationStatus?: string | undefined;
  created?: string | undefined;
};

export const BeneficialOwner$zodSchema: z.ZodType<
  BeneficialOwner,
  z.ZodTypeDef,
  unknown
> = z.object({
  _links: z.record(HalLink$zodSchema).optional(),
  created: z.string().datetime({ offset: true }).optional(),
  id: z.string().optional(),
  verificationStatus: z.string().optional(),
}).describe("Request body model for a Beneficial Owner");
