/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { HalLink, HalLink$zodSchema } from "./hallink.js";

export type BeneficialOwnershipLinks = { self?: HalLink | undefined };

export const BeneficialOwnershipLinks$zodSchema: z.ZodType<
  BeneficialOwnershipLinks
> = z.object({
  self: HalLink$zodSchema.optional(),
});

export const BeneficialOwnershipStatus = {
  Uncertified: "uncertified",
  Certified: "certified",
  Recertify: "recertify",
} as const;
export type BeneficialOwnershipStatus = ClosedEnum<
  typeof BeneficialOwnershipStatus
>;

export const BeneficialOwnershipStatus$zodSchema = z.enum([
  "uncertified",
  "certified",
  "recertify",
]);

export type BeneficialOwnership = {
  _links: BeneficialOwnershipLinks;
  status: BeneficialOwnershipStatus;
};

export const BeneficialOwnership$zodSchema: z.ZodType<BeneficialOwnership> = z
  .object({
    _links: z.lazy(() => BeneficialOwnershipLinks$zodSchema),
    status: BeneficialOwnershipStatus$zodSchema,
  });
