/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { HalLink, HalLink$zodSchema } from "./hallink.js";

export const VerificationStatus$zodSchema = z.enum([
  "verified",
  "document",
  "incomplete",
]);

export type VerificationStatus = z.infer<typeof VerificationStatus$zodSchema>;

/**
 * Request body model for a Beneficial Owner
 */
export type BeneficialOwner = {
  _links: { [k: string]: HalLink };
  id: string;
  verificationStatus: VerificationStatus;
  created: string;
};

export const BeneficialOwner$zodSchema: z.ZodType<
  BeneficialOwner,
  z.ZodTypeDef,
  unknown
> = z.object({
  _links: z.record(HalLink$zodSchema),
  created: z.string().datetime({ offset: true }),
  id: z.string(),
  verificationStatus: VerificationStatus$zodSchema,
}).describe("Request body model for a Beneficial Owner");
