/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  BusinessClassification,
  BusinessClassification$zodSchema,
} from "./businessclassification.js";
import { HalLink, HalLink$zodSchema } from "./hallink.js";

export type BusinessClassificationsEmbedded = {
  businessClassifications?: Array<BusinessClassification> | undefined;
};

export const BusinessClassificationsEmbedded$zodSchema: z.ZodType<
  BusinessClassificationsEmbedded,
  z.ZodTypeDef,
  unknown
> = z.object({
  businessClassifications: z.array(BusinessClassification$zodSchema).optional(),
});

export type BusinessClassifications = {
  _links?: { [k: string]: HalLink } | undefined;
  _embedded?: BusinessClassificationsEmbedded | undefined;
  total?: number | undefined;
};

export const BusinessClassifications$zodSchema: z.ZodType<
  BusinessClassifications,
  z.ZodTypeDef,
  unknown
> = z.object({
  _embedded: z.lazy(() => BusinessClassificationsEmbedded$zodSchema).optional(),
  _links: z.record(HalLink$zodSchema).optional(),
  total: z.number().int().optional(),
});
