/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Document, Document$zodSchema } from "./document.js";
import { HalLink, HalLink$zodSchema } from "./hallink.js";

export type DocumentsEmbedded = { documents: Array<Document> };

export const DocumentsEmbedded$zodSchema: z.ZodType<DocumentsEmbedded> = z
  .object({
    documents: z.array(Document$zodSchema),
  });

export type Documents = {
  _links: { [k: string]: HalLink };
  _embedded: DocumentsEmbedded;
  total: number;
};

export const Documents$zodSchema: z.ZodType<Documents> = z.object({
  _embedded: z.lazy(() => DocumentsEmbedded$zodSchema),
  _links: z.record(z.string(), HalLink$zodSchema),
  total: z.int(),
});
