/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { HalLink, HalLink$zodSchema } from "./hallink.js";

export type Event = {
  _links?: { [k: string]: HalLink } | undefined;
  id?: string | undefined;
  created?: string | undefined;
  topic?: string | undefined;
  resourceId?: string | undefined;
};

export const Event$zodSchema: z.ZodType<Event> = z.object({
  _links: z.record(z.string(), HalLink$zodSchema).optional(),
  created: z.iso.datetime({ offset: true }).optional(),
  id: z.string().optional(),
  resourceId: z.string().optional(),
  topic: z.string().optional(),
});
