/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { HalLink, HalLink$zodSchema } from "./hallink.js";

export const Name$zodSchema = z.enum([
  "MX",
  "Plaid",
  "Flinks",
  "Finicity",
]);

export type Name = z.infer<typeof Name$zodSchema>;

export const ExchangePartnerStatus$zodSchema = z.enum([
  "active",
]);

export type ExchangePartnerStatus = z.infer<
  typeof ExchangePartnerStatus$zodSchema
>;

export type ExchangePartner = {
  _links: { [k: string]: HalLink };
  id: string;
  name: Name;
  status: ExchangePartnerStatus;
  created: string;
};

export const ExchangePartner$zodSchema: z.ZodType<
  ExchangePartner,
  z.ZodTypeDef,
  unknown
> = z.object({
  _links: z.record(HalLink$zodSchema),
  created: z.string().datetime({ offset: true }),
  id: z.string(),
  name: Name$zodSchema,
  status: ExchangePartnerStatus$zodSchema,
});
