/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Exchange, Exchange$zodSchema } from "./exchange.js";
import { HalLink, HalLink$zodSchema } from "./hallink.js";

export type ExchangesEmbedded = { exchanges: Array<Exchange> };

export const ExchangesEmbedded$zodSchema: z.ZodType<ExchangesEmbedded> = z
  .object({
    exchanges: z.array(Exchange$zodSchema),
  });

export type Exchanges = {
  _links: { [k: string]: HalLink };
  _embedded: ExchangesEmbedded;
  total: number;
};

export const Exchanges$zodSchema: z.ZodType<Exchanges> = z.object({
  _embedded: z.lazy(() => ExchangesEmbedded$zodSchema),
  _links: z.record(z.string(), HalLink$zodSchema),
  total: z.int(),
});
