/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { HalLink, HalLink$zodSchema } from "./hallink.js";

export const Channel = {
  Ach: "ach",
  RealTimePayments: "real-time-payments",
  Wire: "wire",
  External: "external",
} as const;
export type Channel = ClosedEnum<typeof Channel>;

export const Channel$zodSchema = z.enum([
  "ach",
  "real-time-payments",
  "wire",
  "external",
]);

export type FundingSource = {
  _links?: { [k: string]: HalLink } | undefined;
  id?: string | undefined;
  status?: string | undefined;
  type?: string | undefined;
  bankAccountType?: string | undefined;
  name?: string | undefined;
  created?: string | undefined;
  removed?: boolean | undefined;
  channels?: Array<Channel> | undefined;
  bankName?: string | undefined;
  fingerprint?: string | undefined;
};

export const FundingSource$zodSchema: z.ZodType<FundingSource> = z.object({
  _links: z.record(z.string(), HalLink$zodSchema).optional(),
  bankAccountType: z.string().optional(),
  bankName: z.string().optional(),
  channels: z.array(Channel$zodSchema).optional(),
  created: z.iso.datetime({ offset: true }).optional(),
  fingerprint: z.string().optional(),
  id: z.string().optional(),
  name: z.string().optional(),
  removed: z.boolean().optional(),
  status: z.string().optional(),
  type: z.string().optional(),
});
