/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Account, Account$zodSchema } from "./account.js";
import { NotFoundError, NotFoundError$zodSchema } from "./notfounderror.js";

export type GetAccountRequest = { id: string };

export const GetAccountRequest$zodSchema: z.ZodType<GetAccountRequest> = z
  .object({
    id: z.string().describe("Account's unique identifier"),
  });

/**
 * forbidden
 */
export type GetAccountResponseBody = {
  code?: string | undefined;
  message?: string | undefined;
};

export const GetAccountResponseBody$zodSchema: z.ZodType<
  GetAccountResponseBody
> = z.object({
  code: z.string().optional(),
  message: z.string().optional(),
}).describe("forbidden");

export type GetAccountResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  Account?: Account | undefined;
  object?: GetAccountResponseBody | undefined;
  NotFoundError?: NotFoundError | undefined;
};

export const GetAccountResponse$zodSchema: z.ZodType<GetAccountResponse> = z
  .object({
    Account: Account$zodSchema.optional().describe("successful operation"),
    ContentType: z.string().describe(
      "HTTP response content type for this operation",
    ),
    NotFoundError: NotFoundError$zodSchema.optional().describe("not found"),
    RawResponse: z.custom<Response>(x => x instanceof Response).describe(
      "Raw HTTP response; suitable for custom response parsing",
    ),
    StatusCode: z.int().describe(
      "HTTP response status code for this operation",
    ),
    object: z.lazy(() => GetAccountResponseBody$zodSchema).optional().describe(
      "forbidden",
    ),
  });
