/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  BeneficialOwnership,
  BeneficialOwnership$zodSchema,
} from "./beneficialownership.js";

export type GetBeneficialOwnershipStatusForCustomerRequest = { id: string };

export const GetBeneficialOwnershipStatusForCustomerRequest$zodSchema:
  z.ZodType<GetBeneficialOwnershipStatusForCustomerRequest> = z.object({
    id: z.string().describe("Customer unique identifier"),
  });

/**
 * not found
 */
export type GetBeneficialOwnershipStatusForCustomerNotFoundResponseBody = {
  code?: string | undefined;
  message?: string | undefined;
};

export const GetBeneficialOwnershipStatusForCustomerNotFoundResponseBody$zodSchema:
  z.ZodType<GetBeneficialOwnershipStatusForCustomerNotFoundResponseBody> = z
    .object({
      code: z.string().optional(),
      message: z.string().optional(),
    }).describe("not found");

/**
 * forbidden
 */
export type GetBeneficialOwnershipStatusForCustomerForbiddenResponseBody = {
  code?: string | undefined;
  message?: string | undefined;
};

export const GetBeneficialOwnershipStatusForCustomerForbiddenResponseBody$zodSchema:
  z.ZodType<GetBeneficialOwnershipStatusForCustomerForbiddenResponseBody> = z
    .object({
      code: z.string().optional(),
      message: z.string().optional(),
    }).describe("forbidden");

export type GetBeneficialOwnershipStatusForCustomerResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  BeneficialOwnership?: BeneficialOwnership | undefined;
  fourHundredAndThreeApplicationVndDwollaV1HalPlusJsonObject?:
    | GetBeneficialOwnershipStatusForCustomerForbiddenResponseBody
    | undefined;
  fourHundredAndFourApplicationVndDwollaV1HalPlusJsonObject?:
    | GetBeneficialOwnershipStatusForCustomerNotFoundResponseBody
    | undefined;
};

export const GetBeneficialOwnershipStatusForCustomerResponse$zodSchema:
  z.ZodType<GetBeneficialOwnershipStatusForCustomerResponse> = z.object({
    BeneficialOwnership: BeneficialOwnership$zodSchema.optional().describe(
      "successful operation",
    ),
    ContentType: z.string().describe(
      "HTTP response content type for this operation",
    ),
    RawResponse: z.custom<Response>(x => x instanceof Response).describe(
      "Raw HTTP response; suitable for custom response parsing",
    ),
    StatusCode: z.int().describe(
      "HTTP response status code for this operation",
    ),
    fourHundredAndFourApplicationVndDwollaV1HalPlusJsonObject: z.lazy(() =>
      GetBeneficialOwnershipStatusForCustomerNotFoundResponseBody$zodSchema
    ).optional().describe("not found"),
    fourHundredAndThreeApplicationVndDwollaV1HalPlusJsonObject: z.lazy(() =>
      GetBeneficialOwnershipStatusForCustomerForbiddenResponseBody$zodSchema
    ).optional().describe("forbidden"),
  });
