/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Customer, Customer$zodSchema } from "./customer.js";

export type GetCustomerRequest = { id: string };

export const GetCustomerRequest$zodSchema: z.ZodType<
  GetCustomerRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().describe("Customer unique identifier"),
});

/**
 * not found
 */
export type GetCustomerNotFoundResponseBody = {
  code?: string | undefined;
  message?: string | undefined;
};

export const GetCustomerNotFoundResponseBody$zodSchema: z.ZodType<
  GetCustomerNotFoundResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string().optional(),
  message: z.string().optional(),
}).describe("not found");

/**
 * forbidden
 */
export type GetCustomerForbiddenResponseBody = {
  code?: string | undefined;
  message?: string | undefined;
};

export const GetCustomerForbiddenResponseBody$zodSchema: z.ZodType<
  GetCustomerForbiddenResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string().optional(),
  message: z.string().optional(),
}).describe("forbidden");

export type GetCustomerResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  Customer?: Customer | undefined;
  fourHundredAndThreeApplicationVndDwollaV1HalPlusJsonObject?:
    | GetCustomerForbiddenResponseBody
    | undefined;
  fourHundredAndFourApplicationVndDwollaV1HalPlusJsonObject?:
    | GetCustomerNotFoundResponseBody
    | undefined;
};

export const GetCustomerResponse$zodSchema: z.ZodType<
  GetCustomerResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  Customer: Customer$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  fourHundredAndFourApplicationVndDwollaV1HalPlusJsonObject: z.lazy(() =>
    GetCustomerNotFoundResponseBody$zodSchema
  ).optional(),
  fourHundredAndThreeApplicationVndDwollaV1HalPlusJsonObject: z.lazy(() =>
    GetCustomerForbiddenResponseBody$zodSchema
  ).optional(),
});
