/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Document, Document$zodSchema } from "./document.js";
import { ForbiddenError, ForbiddenError$zodSchema } from "./forbiddenerror.js";
import { NotFoundError, NotFoundError$zodSchema } from "./notfounderror.js";

export type GetDocumentRequest = { id: string };

export const GetDocumentRequest$zodSchema: z.ZodType<
  GetDocumentRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().describe("Document unique identifier"),
});

export type GetDocumentResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  Document?: Document | undefined;
  ForbiddenError?: ForbiddenError | undefined;
  NotFoundError?: NotFoundError | undefined;
};

export const GetDocumentResponse$zodSchema: z.ZodType<
  GetDocumentResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  Document: Document$zodSchema.optional(),
  ForbiddenError: ForbiddenError$zodSchema.optional(),
  NotFoundError: NotFoundError$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
