/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { FundingSource, FundingSource$zodSchema } from "./fundingsource.js";

export type GetFundingSourceRequest = { id: string };

export const GetFundingSourceRequest$zodSchema: z.ZodType<
  GetFundingSourceRequest
> = z.object({
  id: z.string().describe("Funding source unique identifier"),
});

/**
 * not found
 */
export type GetFundingSourceResponseBody = {
  code?: string | undefined;
  message?: string | undefined;
};

export const GetFundingSourceResponseBody$zodSchema: z.ZodType<
  GetFundingSourceResponseBody
> = z.object({
  code: z.string().optional(),
  message: z.string().optional(),
}).describe("not found");

export type GetFundingSourceResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  FundingSource?: FundingSource | undefined;
  object?: GetFundingSourceResponseBody | undefined;
};

export const GetFundingSourceResponse$zodSchema: z.ZodType<
  GetFundingSourceResponse
> = z.object({
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  FundingSource: FundingSource$zodSchema.optional().describe(
    "successful operation",
  ),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  object: z.lazy(() => GetFundingSourceResponseBody$zodSchema).optional()
    .describe("not found"),
});
