/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { HalLink, HalLink$zodSchema } from "./hallink.js";
import { NotFoundError, NotFoundError$zodSchema } from "./notfounderror.js";

export type GetMicroDepositsRequest = { id: string };

export const GetMicroDepositsRequest$zodSchema: z.ZodType<
  GetMicroDepositsRequest
> = z.object({
  id: z.string().describe(
    "The ID of the FS that previously had micro-deposits initiated",
  ),
});

export type Failure = {
  code?: string | undefined;
  description?: string | undefined;
};

export const Failure$zodSchema: z.ZodType<Failure> = z.object({
  code: z.string().optional(),
  description: z.string().optional(),
});

/**
 * ACH details for the first micro-deposit
 */
export type Deposit1 = { traceId: string };

export const Deposit1$zodSchema: z.ZodType<Deposit1> = z.object({
  traceId: z.string().describe(
    "A unique identifier for tracing the ACH transaction through the banking network. Used for transaction tracking and reconciliation purposes",
  ),
}).describe("ACH details for the first micro-deposit");

/**
 * ACH details for the second micro-deposit
 */
export type Deposit2 = { traceId: string };

export const Deposit2$zodSchema: z.ZodType<Deposit2> = z.object({
  traceId: z.string().describe(
    "A unique identifier for tracing the ACH transaction through the banking network. Used for transaction tracking and reconciliation purposes",
  ),
}).describe("ACH details for the second micro-deposit");

/**
 * ACH details for each micro-deposit. Optional; only returned when ACH details are available for the micro-deposits. `deposit1` or `deposit2` may be omitted if details for that deposit are unavailable.
 */
export type GetMicroDepositsAchDetails = {
  deposit1?: Deposit1 | undefined;
  deposit2?: Deposit2 | undefined;
};

export const GetMicroDepositsAchDetails$zodSchema: z.ZodType<
  GetMicroDepositsAchDetails
> = z.object({
  deposit1: z.lazy(() => Deposit1$zodSchema).optional().describe(
    "ACH details for the first micro-deposit",
  ),
  deposit2: z.lazy(() => Deposit2$zodSchema).optional().describe(
    "ACH details for the second micro-deposit",
  ),
}).describe(
  "ACH details for each micro-deposit. Optional; only returned when ACH details are available for the micro-deposits. `deposit1` or `deposit2` may be omitted if details for that deposit are unavailable.",
);

/**
 * successful operation
 */
export type GetMicroDepositsResponseBody = {
  _links?: { [k: string]: HalLink } | undefined;
  created?: string | undefined;
  status?: string | undefined;
  failure?: Failure | undefined;
  achDetails?: GetMicroDepositsAchDetails | undefined;
};

export const GetMicroDepositsResponseBody$zodSchema: z.ZodType<
  GetMicroDepositsResponseBody
> = z.object({
  _links: z.record(z.string(), HalLink$zodSchema).optional(),
  achDetails: z.lazy(() => GetMicroDepositsAchDetails$zodSchema).optional()
    .describe(
      "ACH details for each micro-deposit. Optional; only returned when ACH details are available for the micro-deposits. `deposit1` or `deposit2` may be omitted if details for that deposit are unavailable.",
    ),
  created: z.iso.datetime({ offset: true }).optional(),
  failure: z.lazy(() => Failure$zodSchema).optional(),
  status: z.string().optional(),
}).describe("successful operation");

export type GetMicroDepositsResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: GetMicroDepositsResponseBody | undefined;
  NotFoundError?: NotFoundError | undefined;
};

export const GetMicroDepositsResponse$zodSchema: z.ZodType<
  GetMicroDepositsResponse
> = z.object({
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  NotFoundError: NotFoundError$zodSchema.optional().describe("not found"),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  object: z.lazy(() => GetMicroDepositsResponseBody$zodSchema).optional()
    .describe("successful operation"),
});
