/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type InternationalAddress = {
  address1: string;
  address2?: string | undefined;
  address3?: string | undefined;
  city: string;
  postalCode?: string | undefined;
  country: string;
  stateProvinceRegion: string;
};

export const InternationalAddress$zodSchema: z.ZodType<
  InternationalAddress,
  z.ZodTypeDef,
  unknown
> = z.object({
  address1: z.string(),
  address2: z.string().optional(),
  address3: z.string().optional(),
  city: z.string(),
  country: z.string(),
  postalCode: z.string().optional(),
  stateProvinceRegion: z.string(),
});
