/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  BeneficialOwners,
  BeneficialOwners$zodSchema,
} from "./beneficialowners.js";

export type ListBeneficialOwnersForCustomerRequest = { id: string };

export const ListBeneficialOwnersForCustomerRequest$zodSchema: z.ZodType<
  ListBeneficialOwnersForCustomerRequest
> = z.object({
  id: z.string().describe("Customer unique identifier"),
});

/**
 * not found
 */
export type ListBeneficialOwnersForCustomerResponseBody = {
  code?: string | undefined;
  message?: string | undefined;
};

export const ListBeneficialOwnersForCustomerResponseBody$zodSchema: z.ZodType<
  ListBeneficialOwnersForCustomerResponseBody
> = z.object({
  code: z.string().optional(),
  message: z.string().optional(),
}).describe("not found");

export type ListBeneficialOwnersForCustomerResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  BeneficialOwners?: BeneficialOwners | undefined;
  object?: ListBeneficialOwnersForCustomerResponseBody | undefined;
};

export const ListBeneficialOwnersForCustomerResponse$zodSchema: z.ZodType<
  ListBeneficialOwnersForCustomerResponse
> = z.object({
  BeneficialOwners: BeneficialOwners$zodSchema.optional().describe(
    "successful operation",
  ),
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  object: z.lazy(() => ListBeneficialOwnersForCustomerResponseBody$zodSchema)
    .optional().describe("not found"),
});
