/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Exchanges, Exchanges$zodSchema } from "./exchanges.js";

export type ListCustomerExchangesRequest = { id: string };

export const ListCustomerExchangesRequest$zodSchema: z.ZodType<
  ListCustomerExchangesRequest
> = z.object({
  id: z.string().describe("The ID of the Customer to list exchanges for"),
});

/**
 * Not Found
 */
export type ListCustomerExchangesResponseBody = {
  code?: string | undefined;
  message?: string | undefined;
};

export const ListCustomerExchangesResponseBody$zodSchema: z.ZodType<
  ListCustomerExchangesResponseBody
> = z.object({
  code: z.string().optional(),
  message: z.string().optional(),
}).describe("Not Found");

export type ListCustomerExchangesResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  Exchanges?: Exchanges | undefined;
  object?: ListCustomerExchangesResponseBody | undefined;
};

export const ListCustomerExchangesResponse$zodSchema: z.ZodType<
  ListCustomerExchangesResponse
> = z.object({
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  Exchanges: Exchanges$zodSchema.optional().describe("successful operation"),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  object: z.lazy(() => ListCustomerExchangesResponseBody$zodSchema).optional()
    .describe("Not Found"),
});
