/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  MassPaymentItem,
  MassPaymentItem$zodSchema,
} from "./masspaymentitem.js";

export type ListMassPaymentItemsRequest = {
  id: string;
  limit?: string | undefined;
  offset?: string | undefined;
  status?: string | undefined;
};

export const ListMassPaymentItemsRequest$zodSchema: z.ZodType<
  ListMassPaymentItemsRequest
> = z.object({
  id: z.string().describe("Mass payment unique identifier"),
  limit: z.string().describe("How many results to return").optional(),
  offset: z.string().describe("How many results to skip").optional(),
  status: z.string().describe("Filter by item status").optional(),
});

/**
 * Mass payment not found
 */
export type ListMassPaymentItemsNotFoundResponseBody = {
  code?: string | undefined;
  message?: string | undefined;
};

export const ListMassPaymentItemsNotFoundResponseBody$zodSchema: z.ZodType<
  ListMassPaymentItemsNotFoundResponseBody
> = z.object({
  code: z.string().optional(),
  message: z.string().optional(),
}).describe("Mass payment not found");

/**
 * Not authorized to list mass payment items
 */
export type ListMassPaymentItemsForbiddenResponseBody = {
  code?: string | undefined;
  message?: string | undefined;
};

export const ListMassPaymentItemsForbiddenResponseBody$zodSchema: z.ZodType<
  ListMassPaymentItemsForbiddenResponseBody
> = z.object({
  code: z.string().optional(),
  message: z.string().optional(),
}).describe("Not authorized to list mass payment items");

export type ListMassPaymentItemsSelf = { href?: string | undefined };

export const ListMassPaymentItemsSelf$zodSchema: z.ZodType<
  ListMassPaymentItemsSelf
> = z.object({
  href: z.string().optional(),
});

export type ListMassPaymentItemsFirst = { href?: string | undefined };

export const ListMassPaymentItemsFirst$zodSchema: z.ZodType<
  ListMassPaymentItemsFirst
> = z.object({
  href: z.string().optional(),
});

export type ListMassPaymentItemsLast = { href?: string | undefined };

export const ListMassPaymentItemsLast$zodSchema: z.ZodType<
  ListMassPaymentItemsLast
> = z.object({
  href: z.string().optional(),
});

export type ListMassPaymentItemsLinks = {
  self?: ListMassPaymentItemsSelf | undefined;
  first?: ListMassPaymentItemsFirst | undefined;
  last?: ListMassPaymentItemsLast | undefined;
};

export const ListMassPaymentItemsLinks$zodSchema: z.ZodType<
  ListMassPaymentItemsLinks
> = z.object({
  first: z.lazy(() => ListMassPaymentItemsFirst$zodSchema).optional(),
  last: z.lazy(() => ListMassPaymentItemsLast$zodSchema).optional(),
  self: z.lazy(() => ListMassPaymentItemsSelf$zodSchema).optional(),
});

export type ListMassPaymentItemsEmbedded = {
  items?: Array<MassPaymentItem> | undefined;
};

export const ListMassPaymentItemsEmbedded$zodSchema: z.ZodType<
  ListMassPaymentItemsEmbedded
> = z.object({
  items: z.array(MassPaymentItem$zodSchema).optional(),
});

/**
 * successful operation
 */
export type ListMassPaymentItemsResponseBody = {
  _links?: ListMassPaymentItemsLinks | undefined;
  _embedded?: ListMassPaymentItemsEmbedded | undefined;
  total?: number | undefined;
};

export const ListMassPaymentItemsResponseBody$zodSchema: z.ZodType<
  ListMassPaymentItemsResponseBody
> = z.object({
  _embedded: z.lazy(() => ListMassPaymentItemsEmbedded$zodSchema).optional(),
  _links: z.lazy(() => ListMassPaymentItemsLinks$zodSchema).optional(),
  total: z.int().optional(),
}).describe("successful operation");

export type ListMassPaymentItemsResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredApplicationVndDwollaV1HalPlusJsonObject?:
    | ListMassPaymentItemsResponseBody
    | undefined;
  fourHundredAndThreeApplicationVndDwollaV1HalPlusJsonObject?:
    | ListMassPaymentItemsForbiddenResponseBody
    | undefined;
  fourHundredAndFourApplicationVndDwollaV1HalPlusJsonObject?:
    | ListMassPaymentItemsNotFoundResponseBody
    | undefined;
};

export const ListMassPaymentItemsResponse$zodSchema: z.ZodType<
  ListMassPaymentItemsResponse
> = z.object({
  ContentType: z.string(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  fourHundredAndFourApplicationVndDwollaV1HalPlusJsonObject: z.lazy(() =>
    ListMassPaymentItemsNotFoundResponseBody$zodSchema
  ).optional(),
  fourHundredAndThreeApplicationVndDwollaV1HalPlusJsonObject: z.lazy(() =>
    ListMassPaymentItemsForbiddenResponseBody$zodSchema
  ).optional(),
  twoHundredApplicationVndDwollaV1HalPlusJsonObject: z.lazy(() =>
    ListMassPaymentItemsResponseBody$zodSchema
  ).optional(),
});
