/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { FundingSources, FundingSources$zodSchema } from "./fundingsources.js";

export type ListCustomerFundingSourcesRequest = {
  id: string;
  removed?: string | undefined;
};

export const ListCustomerFundingSourcesRequest$zodSchema: z.ZodType<
  ListCustomerFundingSourcesRequest
> = z.object({
  id: z.string().describe("Customer's unique identifier"),
  removed: z.string().describe(
    "Filter removed funding sources. Boolean value. Defaults to `true`",
  ).optional(),
});

/**
 * not found
 */
export type ListCustomerFundingSourcesNotFoundResponseBody = {
  code?: string | undefined;
  message?: string | undefined;
};

export const ListCustomerFundingSourcesNotFoundResponseBody$zodSchema:
  z.ZodType<ListCustomerFundingSourcesNotFoundResponseBody> = z.object({
    code: z.string().optional(),
    message: z.string().optional(),
  }).describe("not found");

/**
 * forbidden
 */
export type ListCustomerFundingSourcesForbiddenResponseBody = {
  code?: string | undefined;
  message?: string | undefined;
};

export const ListCustomerFundingSourcesForbiddenResponseBody$zodSchema:
  z.ZodType<ListCustomerFundingSourcesForbiddenResponseBody> = z.object({
    code: z.string().optional(),
    message: z.string().optional(),
  }).describe("forbidden");

export type ListCustomerFundingSourcesResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  FundingSources?: FundingSources | undefined;
  fourHundredAndThreeApplicationVndDwollaV1HalPlusJsonObject?:
    | ListCustomerFundingSourcesForbiddenResponseBody
    | undefined;
  fourHundredAndFourApplicationVndDwollaV1HalPlusJsonObject?:
    | ListCustomerFundingSourcesNotFoundResponseBody
    | undefined;
};

export const ListCustomerFundingSourcesResponse$zodSchema: z.ZodType<
  ListCustomerFundingSourcesResponse
> = z.object({
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  FundingSources: FundingSources$zodSchema.optional().describe(
    "successful operation",
  ),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  fourHundredAndFourApplicationVndDwollaV1HalPlusJsonObject: z.lazy(() =>
    ListCustomerFundingSourcesNotFoundResponseBody$zodSchema
  ).optional().describe("not found"),
  fourHundredAndThreeApplicationVndDwollaV1HalPlusJsonObject: z.lazy(() =>
    ListCustomerFundingSourcesForbiddenResponseBody$zodSchema
  ).optional().describe("forbidden"),
});
