/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  BusinessClassifications,
  BusinessClassifications$zodSchema,
} from "./businessclassifications.js";
import { ForbiddenError, ForbiddenError$zodSchema } from "./forbiddenerror.js";
import { NotFoundError, NotFoundError$zodSchema } from "./notfounderror.js";

export type ListBusinessClassificationsResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  BusinessClassifications?: BusinessClassifications | undefined;
  ForbiddenError?: ForbiddenError | undefined;
  NotFoundError?: NotFoundError | undefined;
};

export const ListBusinessClassificationsResponse$zodSchema: z.ZodType<
  ListBusinessClassificationsResponse
> = z.object({
  BusinessClassifications: BusinessClassifications$zodSchema.optional(),
  ContentType: z.string(),
  ForbiddenError: ForbiddenError$zodSchema.optional(),
  NotFoundError: NotFoundError$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
});
