/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Labels, Labels$zodSchema } from "./labels.js";

export type ListCustomerLabelsRequest = {
  id: string;
  limit?: string | undefined;
  offset?: string | undefined;
};

export const ListCustomerLabelsRequest$zodSchema: z.ZodType<
  ListCustomerLabelsRequest
> = z.object({
  id: z.string().describe("ID of customer"),
  limit: z.string().describe("How many results to return").optional(),
  offset: z.string().describe("How many results to skip").optional(),
});

/**
 * Not Found
 */
export type ListCustomerLabelsNotFoundResponseBody = {
  code?: string | undefined;
  message?: string | undefined;
};

export const ListCustomerLabelsNotFoundResponseBody$zodSchema: z.ZodType<
  ListCustomerLabelsNotFoundResponseBody
> = z.object({
  code: z.string().optional(),
  message: z.string().optional(),
}).describe("Not Found");

/**
 * Forbidden
 */
export type ListCustomerLabelsForbiddenResponseBody = {
  code?: string | undefined;
  message?: string | undefined;
};

export const ListCustomerLabelsForbiddenResponseBody$zodSchema: z.ZodType<
  ListCustomerLabelsForbiddenResponseBody
> = z.object({
  code: z.string().optional(),
  message: z.string().optional(),
}).describe("Forbidden");

export type ListCustomerLabelsResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  Labels?: Labels | undefined;
  fourHundredAndThreeApplicationVndDwollaV1HalPlusJsonObject?:
    | ListCustomerLabelsForbiddenResponseBody
    | undefined;
  fourHundredAndFourApplicationVndDwollaV1HalPlusJsonObject?:
    | ListCustomerLabelsNotFoundResponseBody
    | undefined;
};

export const ListCustomerLabelsResponse$zodSchema: z.ZodType<
  ListCustomerLabelsResponse
> = z.object({
  ContentType: z.string(),
  Labels: Labels$zodSchema.optional(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  fourHundredAndFourApplicationVndDwollaV1HalPlusJsonObject: z.lazy(() =>
    ListCustomerLabelsNotFoundResponseBody$zodSchema
  ).optional(),
  fourHundredAndThreeApplicationVndDwollaV1HalPlusJsonObject: z.lazy(() =>
    ListCustomerLabelsForbiddenResponseBody$zodSchema
  ).optional(),
});
