/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Exchanges, Exchanges$zodSchema } from "./exchanges.js";
import { ForbiddenError, ForbiddenError$zodSchema } from "./forbiddenerror.js";
import { NotFoundError, NotFoundError$zodSchema } from "./notfounderror.js";

export type ListAccountExchangesResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  Exchanges?: Exchanges | undefined;
  ForbiddenError?: ForbiddenError | undefined;
  NotFoundError?: NotFoundError | undefined;
};

export const ListAccountExchangesResponse$zodSchema: z.ZodType<
  ListAccountExchangesResponse
> = z.object({
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  Exchanges: Exchanges$zodSchema.optional().describe("successful operation"),
  ForbiddenError: ForbiddenError$zodSchema.optional().describe("Forbidden"),
  NotFoundError: NotFoundError$zodSchema.optional().describe("Not Found"),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
});
