/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { HalLink, HalLink$zodSchema } from "./hallink.js";

export const ReceiveOnlyCustomerType = {
  ReceiveOnly: "receive-only",
} as const;
export type ReceiveOnlyCustomerType = ClosedEnum<
  typeof ReceiveOnlyCustomerType
>;

export const ReceiveOnlyCustomerType$zodSchema = z.enum([
  "receive-only",
]);

export const ReceiveOnlyCustomerStatus = {
  Unverified: "unverified",
  Suspended: "suspended",
  Deactivated: "deactivated",
} as const;
export type ReceiveOnlyCustomerStatus = ClosedEnum<
  typeof ReceiveOnlyCustomerStatus
>;

export const ReceiveOnlyCustomerStatus$zodSchema = z.enum([
  "unverified",
  "suspended",
  "deactivated",
]);

/**
 * Receive-only user - can only receive funds, not send
 */
export type ReceiveOnlyCustomer = {
  _links: { [k: string]: HalLink };
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  correlationId?: string | undefined;
  created: string;
  type: ReceiveOnlyCustomerType;
  status: ReceiveOnlyCustomerStatus;
  businessName?: string | undefined;
};

export const ReceiveOnlyCustomer$zodSchema: z.ZodType<ReceiveOnlyCustomer> = z
  .object({
    _links: z.record(z.string(), HalLink$zodSchema),
    businessName: z.string().optional(),
    correlationId: z.string().optional(),
    created: z.iso.datetime({ offset: true }),
    email: z.string(),
    firstName: z.string(),
    id: z.string(),
    lastName: z.string(),
    status: ReceiveOnlyCustomerStatus$zodSchema,
    type: ReceiveOnlyCustomerType$zodSchema,
  }).describe("Receive-only user - can only receive funds, not send");
