/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { HalLink, HalLink$zodSchema } from "./hallink.js";

export const ReceiveOnlyCustomerType$zodSchema = z.enum([
  "receive-only",
]);

export type ReceiveOnlyCustomerType = z.infer<
  typeof ReceiveOnlyCustomerType$zodSchema
>;

export const ReceiveOnlyCustomerStatus$zodSchema = z.enum([
  "unverified",
  "suspended",
  "deactivated",
]);

export type ReceiveOnlyCustomerStatus = z.infer<
  typeof ReceiveOnlyCustomerStatus$zodSchema
>;

/**
 * Receive-only user - can only receive funds, not send
 */
export type ReceiveOnlyCustomer = {
  _links: { [k: string]: HalLink };
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  correlationId?: string | undefined;
  created: string;
  type: ReceiveOnlyCustomerType;
  status: ReceiveOnlyCustomerStatus;
  businessName?: string | undefined;
};

export const ReceiveOnlyCustomer$zodSchema: z.ZodType<
  ReceiveOnlyCustomer,
  z.ZodTypeDef,
  unknown
> = z.object({
  _links: z.record(HalLink$zodSchema),
  businessName: z.string().optional(),
  correlationId: z.string().optional(),
  created: z.string().datetime({ offset: true }),
  email: z.string(),
  firstName: z.string(),
  id: z.string(),
  lastName: z.string(),
  status: ReceiveOnlyCustomerStatus$zodSchema,
  type: ReceiveOnlyCustomerType$zodSchema,
}).describe("Receive-only user - can only receive funds, not send");
