/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { HalLink, HalLink$zodSchema } from "./hallink.js";

export type Root = { _links?: { [k: string]: HalLink } | undefined };

export const Root$zodSchema: z.ZodType<Root, z.ZodTypeDef, unknown> = z.object({
  _links: z.record(HalLink$zodSchema).optional(),
});
