/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type TransferAmount = { value: string; currency: string };

export const TransferAmount$zodSchema: z.ZodType<TransferAmount> = z.object({
  currency: z.string(),
  value: z.string(),
});
