/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { HalLink, HalLink$zodSchema } from "./hallink.js";
import { Transfer, Transfer$zodSchema } from "./transfer.js";

export type TransfersEmbedded = { transfers?: Array<Transfer> | undefined };

export const TransfersEmbedded$zodSchema: z.ZodType<
  TransfersEmbedded,
  z.ZodTypeDef,
  unknown
> = z.object({
  transfers: z.array(Transfer$zodSchema).optional(),
});

export type Transfers = {
  _links?: { [k: string]: HalLink } | undefined;
  _embedded?: TransfersEmbedded | undefined;
  total?: number | undefined;
};

export const Transfers$zodSchema: z.ZodType<Transfers, z.ZodTypeDef, unknown> =
  z.object({
    _embedded: z.lazy(() => TransfersEmbedded$zodSchema).optional(),
    _links: z.record(HalLink$zodSchema).optional(),
    total: z.number().int().optional(),
  });
