/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { HalLink, HalLink$zodSchema } from "./hallink.js";

export const UnverifiedCustomerType = {
  Unverified: "unverified",
} as const;
export type UnverifiedCustomerType = ClosedEnum<typeof UnverifiedCustomerType>;

export const UnverifiedCustomerType$zodSchema = z.enum([
  "unverified",
]);

export const UnverifiedCustomerStatus = {
  Unverified: "unverified",
  Suspended: "suspended",
  Deactivated: "deactivated",
} as const;
export type UnverifiedCustomerStatus = ClosedEnum<
  typeof UnverifiedCustomerStatus
>;

export const UnverifiedCustomerStatus$zodSchema = z.enum([
  "unverified",
  "suspended",
  "deactivated",
]);

/**
 * Unverified customer - basic customer type with no KYC verification
 */
export type UnverifiedCustomer = {
  _links: { [k: string]: HalLink };
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  correlationId?: string | undefined;
  created: string;
  type: UnverifiedCustomerType;
  status: UnverifiedCustomerStatus;
  businessName?: string | undefined;
};

export const UnverifiedCustomer$zodSchema: z.ZodType<UnverifiedCustomer> = z
  .object({
    _links: z.record(z.string(), HalLink$zodSchema),
    businessName: z.string().optional(),
    correlationId: z.string().optional(),
    created: z.iso.datetime({ offset: true }),
    email: z.string(),
    firstName: z.string(),
    id: z.string(),
    lastName: z.string(),
    status: UnverifiedCustomerStatus$zodSchema,
    type: UnverifiedCustomerType$zodSchema,
  }).describe(
    "Unverified customer - basic customer type with no KYC verification",
  );
