/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { HalLink, HalLink$zodSchema } from "./hallink.js";

export const VerifiedPersonalCustomerType = {
  Personal: "personal",
} as const;
export type VerifiedPersonalCustomerType = ClosedEnum<
  typeof VerifiedPersonalCustomerType
>;

export const VerifiedPersonalCustomerType$zodSchema = z.enum([
  "personal",
]);

export const VerifiedPersonalCustomerStatus = {
  Verified: "verified",
  Suspended: "suspended",
  Deactivated: "deactivated",
  Document: "document",
  Retry: "retry",
  Kba: "kba",
} as const;
export type VerifiedPersonalCustomerStatus = ClosedEnum<
  typeof VerifiedPersonalCustomerStatus
>;

export const VerifiedPersonalCustomerStatus$zodSchema = z.enum([
  "verified",
  "suspended",
  "deactivated",
  "document",
  "retry",
  "kba",
]);

/**
 * Verified personal customer - fully KYC verified individual with send and receive capabilities
 */
export type VerifiedPersonalCustomer = {
  _links: { [k: string]: HalLink };
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  correlationId?: string | undefined;
  created: string;
  type: VerifiedPersonalCustomerType;
  status: VerifiedPersonalCustomerStatus;
  address1: string;
  address2?: string | undefined;
  city: string;
  state: string;
  postalCode: string;
};

export const VerifiedPersonalCustomer$zodSchema: z.ZodType<
  VerifiedPersonalCustomer
> = z.object({
  _links: z.record(z.string(), HalLink$zodSchema),
  address1: z.string(),
  address2: z.string().optional(),
  city: z.string(),
  correlationId: z.string().optional(),
  created: z.iso.datetime({ offset: true }),
  email: z.string(),
  firstName: z.string(),
  id: z.string(),
  lastName: z.string(),
  postalCode: z.string(),
  state: z.string(),
  status: VerifiedPersonalCustomerStatus$zodSchema,
  type: VerifiedPersonalCustomerType$zodSchema,
}).describe(
  "Verified personal customer - fully KYC verified individual with send and receive capabilities",
);
