/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { HalLink, HalLink$zodSchema } from "./hallink.js";

/**
 * Shared models between all Customer types
 */
export type VerifiedSolePropCustomer = {
  _links?: { [k: string]: HalLink } | undefined;
  id?: string | undefined;
  type?: string | undefined;
  status?: string | undefined;
  correlationId?: string | undefined;
  created?: string | undefined;
  address1?: string | undefined;
  address2?: string | undefined;
  city?: string | undefined;
  state?: string | undefined;
  postalCode?: string | undefined;
  businessName?: string | undefined;
  businessType?: string | undefined;
  businessClassification?: string | undefined;
};

export const VerifiedSolePropCustomer$zodSchema: z.ZodType<
  VerifiedSolePropCustomer,
  z.ZodTypeDef,
  unknown
> = z.object({
  _links: z.record(HalLink$zodSchema).optional(),
  address1: z.string().optional(),
  address2: z.string().optional(),
  businessClassification: z.string().optional(),
  businessName: z.string().optional(),
  businessType: z.string().optional(),
  city: z.string().optional(),
  correlationId: z.string().optional(),
  created: z.string().datetime({ offset: true }).optional(),
  id: z.string().optional(),
  postalCode: z.string().optional(),
  state: z.string().optional(),
  status: z.string().optional(),
  type: z.string().optional(),
}).describe("Shared models between all Customer types");
