/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { HalLink, HalLink$zodSchema } from "./hallink.js";

export const VerifiedSolePropCustomerType = {
  Business: "business",
} as const;
export type VerifiedSolePropCustomerType = ClosedEnum<
  typeof VerifiedSolePropCustomerType
>;

export const VerifiedSolePropCustomerType$zodSchema = z.enum([
  "business",
]);

export const VerifiedSolePropCustomerStatus = {
  Verified: "verified",
  Suspended: "suspended",
  Deactivated: "deactivated",
  Document: "document",
  Retry: "retry",
} as const;
export type VerifiedSolePropCustomerStatus = ClosedEnum<
  typeof VerifiedSolePropCustomerStatus
>;

export const VerifiedSolePropCustomerStatus$zodSchema = z.enum([
  "verified",
  "suspended",
  "deactivated",
  "document",
  "retry",
]);

export const VerifiedSolePropCustomerBusinessType = {
  SoleProprietorship: "soleProprietorship",
} as const;
export type VerifiedSolePropCustomerBusinessType = ClosedEnum<
  typeof VerifiedSolePropCustomerBusinessType
>;

export const VerifiedSolePropCustomerBusinessType$zodSchema = z.enum([
  "soleProprietorship",
]);

/**
 * Verified sole proprietorship customer - distinguished from VerifiedBusinessCustomer by businessType=soleProprietorship
 */
export type VerifiedSolePropCustomer = {
  _links: { [k: string]: HalLink };
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  correlationId?: string | undefined;
  created: string;
  type: VerifiedSolePropCustomerType;
  status: VerifiedSolePropCustomerStatus;
  address1: string;
  address2?: string | undefined;
  city: string;
  state: string;
  postalCode: string;
  businessName: string;
  businessType: VerifiedSolePropCustomerBusinessType;
  businessClassification: string;
};

export const VerifiedSolePropCustomer$zodSchema: z.ZodType<
  VerifiedSolePropCustomer
> = z.object({
  _links: z.record(z.string(), HalLink$zodSchema),
  address1: z.string(),
  address2: z.string().optional(),
  businessClassification: z.string(),
  businessName: z.string(),
  businessType: VerifiedSolePropCustomerBusinessType$zodSchema,
  city: z.string(),
  correlationId: z.string().optional(),
  created: z.iso.datetime({ offset: true }),
  email: z.string(),
  firstName: z.string(),
  id: z.string(),
  lastName: z.string(),
  postalCode: z.string(),
  state: z.string(),
  status: VerifiedSolePropCustomerStatus$zodSchema,
  type: VerifiedSolePropCustomerType$zodSchema,
}).describe(
  "Verified sole proprietorship customer - distinguished from VerifiedBusinessCustomer by businessType=soleProprietorship",
);
