/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type AchAddendaEntriesNotEnabledForAccountErrorLinks = {};

export const AchAddendaEntriesNotEnabledForAccountErrorLinks$zodSchema:
  z.ZodType<
    AchAddendaEntriesNotEnabledForAccountErrorLinks,
    z.ZodTypeDef,
    unknown
  > = z.object({});

export type AchAddendaEntriesNotEnabledForAccountErrorError = {
  code?: string | undefined;
  message?: string | undefined;
  path?: string | undefined;
  _links?: AchAddendaEntriesNotEnabledForAccountErrorLinks | undefined;
};

export const AchAddendaEntriesNotEnabledForAccountErrorError$zodSchema:
  z.ZodType<
    AchAddendaEntriesNotEnabledForAccountErrorError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    _links: z.lazy(() =>
      AchAddendaEntriesNotEnabledForAccountErrorLinks$zodSchema
    ).optional(),
    code: z.string().optional(),
    message: z.string().optional(),
    path: z.string().optional(),
  });

export type AchAddendaEntriesNotEnabledForAccountErrorEmbedded = {
  errors?: Array<AchAddendaEntriesNotEnabledForAccountErrorError> | undefined;
};

export const AchAddendaEntriesNotEnabledForAccountErrorEmbedded$zodSchema:
  z.ZodType<
    AchAddendaEntriesNotEnabledForAccountErrorEmbedded,
    z.ZodTypeDef,
    unknown
  > = z.object({
    errors: z.array(
      z.lazy(() => AchAddendaEntriesNotEnabledForAccountErrorError$zodSchema),
    ).optional(),
  });

export type AchAddendaEntriesNotEnabledForAccountError = {
  code: string;
  message: string;
  _embedded?: AchAddendaEntriesNotEnabledForAccountErrorEmbedded | undefined;
};

export const AchAddendaEntriesNotEnabledForAccountError$zodSchema: z.ZodType<
  AchAddendaEntriesNotEnabledForAccountError,
  z.ZodTypeDef,
  unknown
> = z.object({
  _embedded: z.lazy(() =>
    AchAddendaEntriesNotEnabledForAccountErrorEmbedded$zodSchema
  ).optional(),
  code: z.string(),
  message: z.string(),
});
