/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { HalLink, HalLink$zodSchema } from "./hallink.js";

export type BeneficialOwnershipLinks = { self?: HalLink | undefined };

export const BeneficialOwnershipLinks$zodSchema: z.ZodType<
  BeneficialOwnershipLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  self: HalLink$zodSchema.optional(),
});

export type BeneficialOwnership = {
  _links?: BeneficialOwnershipLinks | undefined;
  status?: string | undefined;
};

export const BeneficialOwnership$zodSchema: z.ZodType<
  BeneficialOwnership,
  z.ZodTypeDef,
  unknown
> = z.object({
  _links: z.lazy(() => BeneficialOwnershipLinks$zodSchema).optional(),
  status: z.string().optional(),
});
