/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  InternationalAddress,
  InternationalAddress$zodSchema,
} from "./internationaladdress.js";
import { Passport, Passport$zodSchema } from "./passport.js";

/**
 * Controller object with Passport
 */
export type ControllerWithPassport = {
  firstName: string;
  lastName: string;
  title: string;
  dateOfBirth: string;
  address: InternationalAddress;
  passport: Passport;
};

export const ControllerWithPassport$zodSchema: z.ZodType<
  ControllerWithPassport,
  z.ZodTypeDef,
  unknown
> = z.object({
  address: InternationalAddress$zodSchema,
  dateOfBirth: z.string().date(),
  firstName: z.string(),
  lastName: z.string(),
  passport: Passport$zodSchema,
  title: z.string(),
}).describe("Controller object with Passport");
