/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Create an Unverified Customer
 */
export type CreateUnverifiedCustomerRequestBody = {
  firstName: string;
  lastName: string;
  email: string;
  ipAddress?: string | undefined;
  phone?: string | undefined;
  correlationId?: string | undefined;
  businessName?: string | undefined;
};

export const CreateUnverifiedCustomerRequestBody$zodSchema: z.ZodType<
  CreateUnverifiedCustomerRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  businessName: z.string().optional(),
  correlationId: z.string().optional(),
  email: z.string(),
  firstName: z.string(),
  ipAddress: z.string().optional(),
  lastName: z.string(),
  phone: z.string().optional(),
}).describe("Create an Unverified Customer");
