/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Create a Receive Only User
 */
export type CreateReceiveOnlyRequestBody = {
  firstName: string;
  lastName: string;
  email: string;
  type: string;
  ipAddress?: string | undefined;
  phone?: string | undefined;
  correlationId?: string | undefined;
  businessName?: string | undefined;
};

export const CreateReceiveOnlyRequestBody$zodSchema: z.ZodType<
  CreateReceiveOnlyRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  businessName: z.string().optional(),
  correlationId: z.string().optional(),
  email: z.string(),
  firstName: z.string(),
  ipAddress: z.string().optional(),
  lastName: z.string(),
  phone: z.string().optional(),
  type: z.string(),
}).describe("Create a Receive Only User");
