/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ControllerWithPassport,
  ControllerWithPassport$zodSchema,
} from "./controllerwithpassport.js";
import {
  ControllerWithSsn,
  ControllerWithSsn$zodSchema,
} from "./controllerwithssn.js";

export type ControllerUnion = ControllerWithSsn | ControllerWithPassport;

export const ControllerUnion$zodSchema: z.ZodType<
  ControllerUnion,
  z.ZodTypeDef,
  unknown
> = z.union([
  ControllerWithSsn$zodSchema,
  ControllerWithPassport$zodSchema,
]);

/**
 * Create a Verified Business customer
 */
export type CreateVerifiedBusinessRequestBody = {
  firstName: string;
  lastName: string;
  email: string;
  ipAddress?: string | undefined;
  phone?: string | undefined;
  correlationId?: string | undefined;
  businessName: string;
  type: string;
  address1: string;
  address2?: string | undefined;
  city: string;
  state: string;
  postalCode: string;
  ssn: string;
  dateOfBirth: string;
  businessClassification: string;
  doingBusinessAs?: string | undefined;
  ein: string;
  website?: string | undefined;
  controller: ControllerWithSsn | ControllerWithPassport;
  businessType: string;
};

export const CreateVerifiedBusinessRequestBody$zodSchema: z.ZodType<
  CreateVerifiedBusinessRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  address1: z.string(),
  address2: z.string().optional(),
  businessClassification: z.string(),
  businessName: z.string(),
  businessType: z.string(),
  city: z.string(),
  controller: z.union([
    ControllerWithSsn$zodSchema,
    ControllerWithPassport$zodSchema,
  ]),
  correlationId: z.string().optional(),
  dateOfBirth: z.string(),
  doingBusinessAs: z.string().optional(),
  ein: z.string(),
  email: z.string(),
  firstName: z.string(),
  ipAddress: z.string().optional(),
  lastName: z.string(),
  phone: z.string().optional(),
  postalCode: z.string(),
  ssn: z.string(),
  state: z.string(),
  type: z.string(),
  website: z.string().optional(),
}).describe("Create a Verified Business customer");
