/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Create a Verified Personal customer
 */
export type CreateVerifiedPersonalRequestBody = {
  firstName: string;
  lastName: string;
  email: string;
  ipAddress?: string | undefined;
  phone?: string | undefined;
  correlationId?: string | undefined;
  businessName?: string | undefined;
  type: string;
  address1: string;
  address2?: string | undefined;
  city: string;
  state: string;
  postalCode: string;
  ssn: string;
  dateOfBirth: string;
};

export const CreateVerifiedPersonalRequestBody$zodSchema: z.ZodType<
  CreateVerifiedPersonalRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  address1: z.string(),
  address2: z.string().optional(),
  businessName: z.string().optional(),
  city: z.string(),
  correlationId: z.string().optional(),
  dateOfBirth: z.string(),
  email: z.string(),
  firstName: z.string(),
  ipAddress: z.string().optional(),
  lastName: z.string(),
  phone: z.string().optional(),
  postalCode: z.string(),
  ssn: z.string(),
  state: z.string(),
  type: z.string(),
}).describe("Create a Verified Personal customer");
