/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CreateFundingSourceForAccountRequestBodyExchange = {
  href?: string | undefined;
};

export const CreateFundingSourceForAccountRequestBodyExchange$zodSchema:
  z.ZodType<
    CreateFundingSourceForAccountRequestBodyExchange,
    z.ZodTypeDef,
    unknown
  > = z.object({
    href: z.string().optional(),
  });

export type CreateFundingSourceForAccountRequestBodyLinks = {
  exchange?: CreateFundingSourceForAccountRequestBodyExchange | undefined;
};

export const CreateFundingSourceForAccountRequestBodyLinks$zodSchema: z.ZodType<
  CreateFundingSourceForAccountRequestBodyLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  exchange: z.lazy(() =>
    CreateFundingSourceForAccountRequestBodyExchange$zodSchema
  ).optional(),
});

export const CreateFundingSourceForAccountRequestBodyBankAccountType$zodSchema =
  z.enum([
    "checking",
    "savings",
  ]);

export type CreateFundingSourceForAccountRequestBodyBankAccountType = z.infer<
  typeof CreateFundingSourceForAccountRequestBodyBankAccountType$zodSchema
>;

export type CreateFundingSourceForAccountRequestBody = {
  _links?: CreateFundingSourceForAccountRequestBodyLinks | undefined;
  name: string;
  bankAccountType: CreateFundingSourceForAccountRequestBodyBankAccountType;
  accountNumber: string;
  routingNumber: string;
  channels?: Array<string> | undefined;
};

export const CreateFundingSourceForAccountRequestBody$zodSchema: z.ZodType<
  CreateFundingSourceForAccountRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  _links: z.lazy(() => CreateFundingSourceForAccountRequestBodyLinks$zodSchema)
    .optional(),
  accountNumber: z.string(),
  bankAccountType:
    CreateFundingSourceForAccountRequestBodyBankAccountType$zodSchema,
  channels: z.array(z.string()).optional(),
  name: z.string(),
  routingNumber: z.string(),
});
