/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Deactivate a Customer
 */
export type DeactivateCustomer = { status: string };

export const DeactivateCustomer$zodSchema: z.ZodType<
  DeactivateCustomer,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.string(),
}).describe("Deactivate a Customer");
