/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DepositAccountRestrictedErrorLinks = {};

export const DepositAccountRestrictedErrorLinks$zodSchema: z.ZodType<
  DepositAccountRestrictedErrorLinks,
  z.ZodTypeDef,
  unknown
> = z.object({});

export type DepositAccountRestrictedErrorError = {
  code?: string | undefined;
  message?: string | undefined;
  path?: string | undefined;
  _links?: DepositAccountRestrictedErrorLinks | undefined;
};

export const DepositAccountRestrictedErrorError$zodSchema: z.ZodType<
  DepositAccountRestrictedErrorError,
  z.ZodTypeDef,
  unknown
> = z.object({
  _links: z.lazy(() => DepositAccountRestrictedErrorLinks$zodSchema).optional(),
  code: z.string().optional(),
  message: z.string().optional(),
  path: z.string().optional(),
});

export type DepositAccountRestrictedErrorEmbedded = {
  errors?: Array<DepositAccountRestrictedErrorError> | undefined;
};

export const DepositAccountRestrictedErrorEmbedded$zodSchema: z.ZodType<
  DepositAccountRestrictedErrorEmbedded,
  z.ZodTypeDef,
  unknown
> = z.object({
  errors: z.array(z.lazy(() => DepositAccountRestrictedErrorError$zodSchema))
    .optional(),
});

export type DepositAccountRestrictedError = {
  code: string;
  message: string;
  _embedded?: DepositAccountRestrictedErrorEmbedded | undefined;
};

export const DepositAccountRestrictedError$zodSchema: z.ZodType<
  DepositAccountRestrictedError,
  z.ZodTypeDef,
  unknown
> = z.object({
  _embedded: z.lazy(() => DepositAccountRestrictedErrorEmbedded$zodSchema)
    .optional(),
  code: z.string(),
  message: z.string(),
});
