/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Document, Document$zodSchema } from "./document.js";
import { HalLink, HalLink$zodSchema } from "./hallink.js";

export type DocumentsEmbedded = { documents?: Array<Document> | undefined };

export const DocumentsEmbedded$zodSchema: z.ZodType<
  DocumentsEmbedded,
  z.ZodTypeDef,
  unknown
> = z.object({
  documents: z.array(Document$zodSchema).optional(),
});

export type Documents = {
  _links?: { [k: string]: HalLink } | undefined;
  _embedded?: DocumentsEmbedded | undefined;
  total?: number | undefined;
};

export const Documents$zodSchema: z.ZodType<Documents, z.ZodTypeDef, unknown> =
  z.object({
    _embedded: z.lazy(() => DocumentsEmbedded$zodSchema).optional(),
    _links: z.record(HalLink$zodSchema).optional(),
    total: z.number().int().optional(),
  });
