/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { HalLink, HalLink$zodSchema } from "./hallink.js";

export type Exchange = {
  _links?: { [k: string]: HalLink } | undefined;
  id?: string | undefined;
  status?: string | undefined;
  created?: string | undefined;
};

export const Exchange$zodSchema: z.ZodType<Exchange, z.ZodTypeDef, unknown> = z
  .object({
    _links: z.record(HalLink$zodSchema).optional(),
    created: z.string().datetime({ offset: true }).optional(),
    id: z.string().optional(),
    status: z.string().optional(),
  });
