/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type FlinksSecureExchangeCreateExchangeRequestBodyExchangePartner = {
  href: string;
};

export const FlinksSecureExchangeCreateExchangeRequestBodyExchangePartner$zodSchema:
  z.ZodType<
    FlinksSecureExchangeCreateExchangeRequestBodyExchangePartner,
    z.ZodTypeDef,
    unknown
  > = z.object({
    href: z.string(),
  });

export type FlinksSecureExchangeCreateExchangeRequestBodyLinks = {
  exchangePartner: FlinksSecureExchangeCreateExchangeRequestBodyExchangePartner;
};

export const FlinksSecureExchangeCreateExchangeRequestBodyLinks$zodSchema:
  z.ZodType<
    FlinksSecureExchangeCreateExchangeRequestBodyLinks,
    z.ZodTypeDef,
    unknown
  > = z.object({
    exchangePartner: z.lazy(() =>
      FlinksSecureExchangeCreateExchangeRequestBodyExchangePartner$zodSchema
    ),
  });

export type FlinksSecureExchangeCreateExchangeRequestBody = {
  _links: FlinksSecureExchangeCreateExchangeRequestBodyLinks;
  token: string;
};

export const FlinksSecureExchangeCreateExchangeRequestBody$zodSchema: z.ZodType<
  FlinksSecureExchangeCreateExchangeRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  _links: z.lazy(() =>
    FlinksSecureExchangeCreateExchangeRequestBodyLinks$zodSchema
  ),
  token: z.string(),
});
