/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type HighRiskErrorLinks = {};

export const HighRiskErrorLinks$zodSchema: z.ZodType<
  HighRiskErrorLinks,
  z.ZodTypeDef,
  unknown
> = z.object({});

export type HighRiskErrorError = {
  code?: string | undefined;
  message?: string | undefined;
  path?: string | undefined;
  _links?: HighRiskErrorLinks | undefined;
};

export const HighRiskErrorError$zodSchema: z.ZodType<
  HighRiskErrorError,
  z.ZodTypeDef,
  unknown
> = z.object({
  _links: z.lazy(() => HighRiskErrorLinks$zodSchema).optional(),
  code: z.string().optional(),
  message: z.string().optional(),
  path: z.string().optional(),
});

export type HighRiskErrorEmbedded = {
  errors?: Array<HighRiskErrorError> | undefined;
};

export const HighRiskErrorEmbedded$zodSchema: z.ZodType<
  HighRiskErrorEmbedded,
  z.ZodTypeDef,
  unknown
> = z.object({
  errors: z.array(z.lazy(() => HighRiskErrorError$zodSchema)).optional(),
});

export type HighRiskError = {
  code: string;
  message: string;
  _embedded?: HighRiskErrorEmbedded | undefined;
};

export const HighRiskError$zodSchema: z.ZodType<
  HighRiskError,
  z.ZodTypeDef,
  unknown
> = z.object({
  _embedded: z.lazy(() => HighRiskErrorEmbedded$zodSchema).optional(),
  code: z.string(),
  message: z.string(),
});
