/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type InvalidPointOfSaleAddendaStateErrorLinks = {};

export const InvalidPointOfSaleAddendaStateErrorLinks$zodSchema: z.ZodType<
  InvalidPointOfSaleAddendaStateErrorLinks,
  z.ZodTypeDef,
  unknown
> = z.object({});

export type InvalidPointOfSaleAddendaStateErrorError = {
  code?: string | undefined;
  message?: string | undefined;
  path?: string | undefined;
  _links?: InvalidPointOfSaleAddendaStateErrorLinks | undefined;
};

export const InvalidPointOfSaleAddendaStateErrorError$zodSchema: z.ZodType<
  InvalidPointOfSaleAddendaStateErrorError,
  z.ZodTypeDef,
  unknown
> = z.object({
  _links: z.lazy(() => InvalidPointOfSaleAddendaStateErrorLinks$zodSchema)
    .optional(),
  code: z.string().optional(),
  message: z.string().optional(),
  path: z.string().optional(),
});

export type InvalidPointOfSaleAddendaStateErrorEmbedded = {
  errors?: Array<InvalidPointOfSaleAddendaStateErrorError> | undefined;
};

export const InvalidPointOfSaleAddendaStateErrorEmbedded$zodSchema: z.ZodType<
  InvalidPointOfSaleAddendaStateErrorEmbedded,
  z.ZodTypeDef,
  unknown
> = z.object({
  errors: z.array(
    z.lazy(() => InvalidPointOfSaleAddendaStateErrorError$zodSchema),
  ).optional(),
});

export type InvalidPointOfSaleAddendaStateError = {
  code: string;
  message: string;
  _embedded?: InvalidPointOfSaleAddendaStateErrorEmbedded | undefined;
};

export const InvalidPointOfSaleAddendaStateError$zodSchema: z.ZodType<
  InvalidPointOfSaleAddendaStateError,
  z.ZodTypeDef,
  unknown
> = z.object({
  _embedded: z.lazy(() => InvalidPointOfSaleAddendaStateErrorEmbedded$zodSchema)
    .optional(),
  code: z.string(),
  message: z.string(),
});
