/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type InvalidResourceStateSchema = { code: string; message: string };

export const InvalidResourceStateSchema$zodSchema: z.ZodType<
  InvalidResourceStateSchema,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string(),
});
