/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type InvalidFacilitatorFeeCollectFromErrorLinks = {};

export const InvalidFacilitatorFeeCollectFromErrorLinks$zodSchema: z.ZodType<
  InvalidFacilitatorFeeCollectFromErrorLinks,
  z.ZodTypeDef,
  unknown
> = z.object({});

export type InvalidFacilitatorFeeCollectFromErrorError = {
  code?: string | undefined;
  message?: string | undefined;
  path?: string | undefined;
  _links?: InvalidFacilitatorFeeCollectFromErrorLinks | undefined;
};

export const InvalidFacilitatorFeeCollectFromErrorError$zodSchema: z.ZodType<
  InvalidFacilitatorFeeCollectFromErrorError,
  z.ZodTypeDef,
  unknown
> = z.object({
  _links: z.lazy(() => InvalidFacilitatorFeeCollectFromErrorLinks$zodSchema)
    .optional(),
  code: z.string().optional(),
  message: z.string().optional(),
  path: z.string().optional(),
});

export type InvalidFacilitatorFeeCollectFromErrorEmbedded = {
  errors?: Array<InvalidFacilitatorFeeCollectFromErrorError> | undefined;
};

export const InvalidFacilitatorFeeCollectFromErrorEmbedded$zodSchema: z.ZodType<
  InvalidFacilitatorFeeCollectFromErrorEmbedded,
  z.ZodTypeDef,
  unknown
> = z.object({
  errors: z.array(
    z.lazy(() => InvalidFacilitatorFeeCollectFromErrorError$zodSchema),
  ).optional(),
});

export type InvalidFacilitatorFeeCollectFromError = {
  code: string;
  message: string;
  _embedded?: InvalidFacilitatorFeeCollectFromErrorEmbedded | undefined;
};

export const InvalidFacilitatorFeeCollectFromError$zodSchema: z.ZodType<
  InvalidFacilitatorFeeCollectFromError,
  z.ZodTypeDef,
  unknown
> = z.object({
  _embedded: z.lazy(() =>
    InvalidFacilitatorFeeCollectFromErrorEmbedded$zodSchema
  ).optional(),
  code: z.string(),
  message: z.string(),
});
