/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type InvalidAttemptToFacilitateFundsError = {
  code: string;
  message: string;
};

export const InvalidAttemptToFacilitateFundsError$zodSchema: z.ZodType<
  InvalidAttemptToFacilitateFundsError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string(),
});
