/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type InvalidMetadataErrorLinks = {};

export const InvalidMetadataErrorLinks$zodSchema: z.ZodType<
  InvalidMetadataErrorLinks,
  z.ZodTypeDef,
  unknown
> = z.object({});

export type InvalidMetadataErrorError = {
  code?: string | undefined;
  message?: string | undefined;
  path?: string | undefined;
  _links?: InvalidMetadataErrorLinks | undefined;
};

export const InvalidMetadataErrorError$zodSchema: z.ZodType<
  InvalidMetadataErrorError,
  z.ZodTypeDef,
  unknown
> = z.object({
  _links: z.lazy(() => InvalidMetadataErrorLinks$zodSchema).optional(),
  code: z.string().optional(),
  message: z.string().optional(),
  path: z.string().optional(),
});

export type InvalidMetadataErrorEmbedded = {
  errors?: Array<InvalidMetadataErrorError> | undefined;
};

export const InvalidMetadataErrorEmbedded$zodSchema: z.ZodType<
  InvalidMetadataErrorEmbedded,
  z.ZodTypeDef,
  unknown
> = z.object({
  errors: z.array(z.lazy(() => InvalidMetadataErrorError$zodSchema)).optional(),
});

export type InvalidMetadataError = {
  code: string;
  message: string;
  _embedded?: InvalidMetadataErrorEmbedded | undefined;
};

export const InvalidMetadataError$zodSchema: z.ZodType<
  InvalidMetadataError,
  z.ZodTypeDef,
  unknown
> = z.object({
  _embedded: z.lazy(() => InvalidMetadataErrorEmbedded$zodSchema).optional(),
  code: z.string(),
  message: z.string(),
});
