/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type InvalidFeeOdfiErrorLinks = {};

export const InvalidFeeOdfiErrorLinks$zodSchema: z.ZodType<
  InvalidFeeOdfiErrorLinks,
  z.ZodTypeDef,
  unknown
> = z.object({});

export type InvalidFeeOdfiErrorError = {
  code?: string | undefined;
  message?: string | undefined;
  path?: string | undefined;
  _links?: InvalidFeeOdfiErrorLinks | undefined;
};

export const InvalidFeeOdfiErrorError$zodSchema: z.ZodType<
  InvalidFeeOdfiErrorError,
  z.ZodTypeDef,
  unknown
> = z.object({
  _links: z.lazy(() => InvalidFeeOdfiErrorLinks$zodSchema).optional(),
  code: z.string().optional(),
  message: z.string().optional(),
  path: z.string().optional(),
});

export type InvalidFeeOdfiErrorEmbedded = {
  errors?: Array<InvalidFeeOdfiErrorError> | undefined;
};

export const InvalidFeeOdfiErrorEmbedded$zodSchema: z.ZodType<
  InvalidFeeOdfiErrorEmbedded,
  z.ZodTypeDef,
  unknown
> = z.object({
  errors: z.array(z.lazy(() => InvalidFeeOdfiErrorError$zodSchema)).optional(),
});

export type InvalidFeeOdfiError = {
  code: string;
  message: string;
  _embedded?: InvalidFeeOdfiErrorEmbedded | undefined;
};

export const InvalidFeeOdfiError$zodSchema: z.ZodType<
  InvalidFeeOdfiError,
  z.ZodTypeDef,
  unknown
> = z.object({
  _embedded: z.lazy(() => InvalidFeeOdfiErrorEmbedded$zodSchema).optional(),
  code: z.string(),
  message: z.string(),
});
