/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { HalLink, HalLink$zodSchema } from "./hallink.js";
import { TransferAmount, TransferAmount$zodSchema } from "./transferamount.js";

export type MassPaymentMetaData = {};

export const MassPaymentMetaData$zodSchema: z.ZodType<
  MassPaymentMetaData,
  z.ZodTypeDef,
  unknown
> = z.object({});

export type MassPayment = {
  _links?: { [k: string]: HalLink } | undefined;
  id?: string | undefined;
  status?: string | undefined;
  created?: string | undefined;
  metaData?: MassPaymentMetaData | undefined;
  total?: TransferAmount | undefined;
  totalFees?: TransferAmount | undefined;
  correlationId?: string | undefined;
};

export const MassPayment$zodSchema: z.ZodType<
  MassPayment,
  z.ZodTypeDef,
  unknown
> = z.object({
  _links: z.record(HalLink$zodSchema).optional(),
  correlationId: z.string().optional(),
  created: z.string().datetime({ offset: true }).optional(),
  id: z.string().optional(),
  metaData: z.lazy(() => MassPaymentMetaData$zodSchema).optional(),
  status: z.string().optional(),
  total: TransferAmount$zodSchema.optional(),
  totalFees: TransferAmount$zodSchema.optional(),
});
