/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type MassPaymentItemSelf = { href?: string | undefined };

export const MassPaymentItemSelf$zodSchema: z.ZodType<
  MassPaymentItemSelf,
  z.ZodTypeDef,
  unknown
> = z.object({
  href: z.string().optional(),
});

export type MassPaymentItemMassPayment = { href?: string | undefined };

export const MassPaymentItemMassPayment$zodSchema: z.ZodType<
  MassPaymentItemMassPayment,
  z.ZodTypeDef,
  unknown
> = z.object({
  href: z.string().optional(),
});

export type MassPaymentItemDestination = { href?: string | undefined };

export const MassPaymentItemDestination$zodSchema: z.ZodType<
  MassPaymentItemDestination,
  z.ZodTypeDef,
  unknown
> = z.object({
  href: z.string().optional(),
});

export type MassPaymentItemTransfer = { href?: string | undefined };

export const MassPaymentItemTransfer$zodSchema: z.ZodType<
  MassPaymentItemTransfer,
  z.ZodTypeDef,
  unknown
> = z.object({
  href: z.string().optional(),
});

export type MassPaymentItemLinks = {
  self?: MassPaymentItemSelf | undefined;
  massPayment?: MassPaymentItemMassPayment | undefined;
  destination?: MassPaymentItemDestination | undefined;
  transfer?: MassPaymentItemTransfer | undefined;
};

export const MassPaymentItemLinks$zodSchema: z.ZodType<
  MassPaymentItemLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  destination: z.lazy(() => MassPaymentItemDestination$zodSchema).optional(),
  massPayment: z.lazy(() => MassPaymentItemMassPayment$zodSchema).optional(),
  self: z.lazy(() => MassPaymentItemSelf$zodSchema).optional(),
  transfer: z.lazy(() => MassPaymentItemTransfer$zodSchema).optional(),
});

export type MassPaymentItemAmount = {
  value?: string | undefined;
  currency?: string | undefined;
};

export const MassPaymentItemAmount$zodSchema: z.ZodType<
  MassPaymentItemAmount,
  z.ZodTypeDef,
  unknown
> = z.object({
  currency: z.string().optional(),
  value: z.string().optional(),
});

export type MassPaymentItemMetadata = { item1?: string | undefined };

export const MassPaymentItemMetadata$zodSchema: z.ZodType<
  MassPaymentItemMetadata,
  z.ZodTypeDef,
  unknown
> = z.object({
  item1: z.string().optional(),
});

export type MassPaymentItemProcessingChannel = {
  destination?: string | undefined;
};

export const MassPaymentItemProcessingChannel$zodSchema: z.ZodType<
  MassPaymentItemProcessingChannel,
  z.ZodTypeDef,
  unknown
> = z.object({
  destination: z.string().optional(),
});

export type MassPaymentItem = {
  _links?: MassPaymentItemLinks | undefined;
  id?: string | undefined;
  status?: string | undefined;
  amount?: MassPaymentItemAmount | undefined;
  metadata?: MassPaymentItemMetadata | undefined;
  processingChannel?: MassPaymentItemProcessingChannel | undefined;
};

export const MassPaymentItem$zodSchema: z.ZodType<
  MassPaymentItem,
  z.ZodTypeDef,
  unknown
> = z.object({
  _links: z.lazy(() => MassPaymentItemLinks$zodSchema).optional(),
  amount: z.lazy(() => MassPaymentItemAmount$zodSchema).optional(),
  id: z.string().optional(),
  metadata: z.lazy(() => MassPaymentItemMetadata$zodSchema).optional(),
  processingChannel: z.lazy(() => MassPaymentItemProcessingChannel$zodSchema)
    .optional(),
  status: z.string().optional(),
});
