/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type MXSecureExchangeCreateExchangeRequestBodyExchangePartner = {
  href?: string | undefined;
};

export const MXSecureExchangeCreateExchangeRequestBodyExchangePartner$zodSchema:
  z.ZodType<
    MXSecureExchangeCreateExchangeRequestBodyExchangePartner,
    z.ZodTypeDef,
    unknown
  > = z.object({
    href: z.string().optional(),
  });

export type MXSecureExchangeCreateExchangeRequestBodyLinks = {
  exchangePartner?:
    | MXSecureExchangeCreateExchangeRequestBodyExchangePartner
    | undefined;
};

export const MXSecureExchangeCreateExchangeRequestBodyLinks$zodSchema:
  z.ZodType<
    MXSecureExchangeCreateExchangeRequestBodyLinks,
    z.ZodTypeDef,
    unknown
  > = z.object({
    exchangePartner: z.lazy(() =>
      MXSecureExchangeCreateExchangeRequestBodyExchangePartner$zodSchema
    ).optional(),
  });

export type MXSecureExchangeCreateExchangeRequestBody = {
  _links?: MXSecureExchangeCreateExchangeRequestBodyLinks | undefined;
  token?: string | undefined;
};

export const MXSecureExchangeCreateExchangeRequestBody$zodSchema: z.ZodType<
  MXSecureExchangeCreateExchangeRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  _links: z.lazy(() => MXSecureExchangeCreateExchangeRequestBodyLinks$zodSchema)
    .optional(),
  token: z.string().optional(),
});
