/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type OnDemandAuthorizationSelf = { href?: string | undefined };

export const OnDemandAuthorizationSelf$zodSchema: z.ZodType<
  OnDemandAuthorizationSelf,
  z.ZodTypeDef,
  unknown
> = z.object({
  href: z.string().optional(),
});

export type OnDemandAuthorizationLinks = {
  self?: OnDemandAuthorizationSelf | undefined;
};

export const OnDemandAuthorizationLinks$zodSchema: z.ZodType<
  OnDemandAuthorizationLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  self: z.lazy(() => OnDemandAuthorizationSelf$zodSchema).optional(),
});

export type OnDemandAuthorization = {
  _links?: OnDemandAuthorizationLinks | undefined;
  bodyText?: string | undefined;
  buttonText?: string | undefined;
};

export const OnDemandAuthorization$zodSchema: z.ZodType<
  OnDemandAuthorization,
  z.ZodTypeDef,
  unknown
> = z.object({
  _links: z.lazy(() => OnDemandAuthorizationLinks$zodSchema).optional(),
  bodyText: z.string().optional(),
  buttonText: z.string().optional(),
});
