/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Passport = { number: string; country: string };

export const Passport$zodSchema: z.ZodType<Passport, z.ZodTypeDef, unknown> = z
  .object({
    country: z.string(),
    number: z.string(),
  });
