/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type PlaidSecureExchangeCreateExchangeRequestBodyExchangePartner = {
  href?: string | undefined;
};

export const PlaidSecureExchangeCreateExchangeRequestBodyExchangePartner$zodSchema:
  z.ZodType<
    PlaidSecureExchangeCreateExchangeRequestBodyExchangePartner,
    z.ZodTypeDef,
    unknown
  > = z.object({
    href: z.string().optional(),
  });

export type PlaidSecureExchangeCreateExchangeRequestBodyLinks = {
  exchangePartner?:
    | PlaidSecureExchangeCreateExchangeRequestBodyExchangePartner
    | undefined;
};

export const PlaidSecureExchangeCreateExchangeRequestBodyLinks$zodSchema:
  z.ZodType<
    PlaidSecureExchangeCreateExchangeRequestBodyLinks,
    z.ZodTypeDef,
    unknown
  > = z.object({
    exchangePartner: z.lazy(() =>
      PlaidSecureExchangeCreateExchangeRequestBodyExchangePartner$zodSchema
    ).optional(),
  });

export type PlaidSecureExchangeCreateExchangeRequestBody = {
  _links?: PlaidSecureExchangeCreateExchangeRequestBodyLinks | undefined;
  token?: string | undefined;
};

export const PlaidSecureExchangeCreateExchangeRequestBody$zodSchema: z.ZodType<
  PlaidSecureExchangeCreateExchangeRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  _links: z.lazy(() =>
    PlaidSecureExchangeCreateExchangeRequestBodyLinks$zodSchema
  ).optional(),
  token: z.string().optional(),
});
