/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type RetryVerifiedBusinessAddress = {
  address1: string;
  address2?: string | undefined;
  city: string;
  stateProvinceRegion: string;
  postalCode: string;
  country: string;
};

export const RetryVerifiedBusinessAddress$zodSchema: z.ZodType<
  RetryVerifiedBusinessAddress,
  z.ZodTypeDef,
  unknown
> = z.object({
  address1: z.string(),
  address2: z.string().optional(),
  city: z.string(),
  country: z.string(),
  postalCode: z.string(),
  stateProvinceRegion: z.string(),
});

export type RetryVerifiedBusinessController = {
  firstName: string;
  lastName: string;
  title: string;
  ssn?: string | undefined;
  dateOfBirth: string;
  address: RetryVerifiedBusinessAddress;
};

export const RetryVerifiedBusinessController$zodSchema: z.ZodType<
  RetryVerifiedBusinessController,
  z.ZodTypeDef,
  unknown
> = z.object({
  address: z.lazy(() => RetryVerifiedBusinessAddress$zodSchema),
  dateOfBirth: z.string().date(),
  firstName: z.string(),
  lastName: z.string(),
  ssn: z.string().optional(),
  title: z.string(),
});

/**
 * Retry Verification for Verified Business Customer
 */
export type RetryVerifiedBusiness = {
  firstName: string;
  lastName: string;
  email: string;
  ipAddress?: string | undefined;
  type: string;
  address1: string;
  city: string;
  state: string;
  postalCode: string;
  controller: RetryVerifiedBusinessController;
  businessClassification: string;
  businessType: string;
  businessName: string;
  ein: string;
};

export const RetryVerifiedBusiness$zodSchema: z.ZodType<
  RetryVerifiedBusiness,
  z.ZodTypeDef,
  unknown
> = z.object({
  address1: z.string(),
  businessClassification: z.string(),
  businessName: z.string(),
  businessType: z.string(),
  city: z.string(),
  controller: z.lazy(() => RetryVerifiedBusinessController$zodSchema),
  ein: z.string(),
  email: z.string(),
  firstName: z.string(),
  ipAddress: z.string().optional(),
  lastName: z.string(),
  postalCode: z.string(),
  state: z.string(),
  type: z.string(),
}).describe("Retry Verification for Verified Business Customer");
