/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Retry Verification for Verified Business Customer (Sole Proprietorship)
 */
export type RetryVerifiedSoleProp = {
  firstName: string;
  lastName: string;
  email: string;
  ipAddress?: string | undefined;
  type: string;
  dateOfBirth: string;
  ssn: string;
  address1: string;
  city: string;
  state: string;
  postalCode: string;
  businessClassification: string;
  businessType: string;
  businessName: string;
  ein: string;
};

export const RetryVerifiedSoleProp$zodSchema: z.ZodType<
  RetryVerifiedSoleProp,
  z.ZodTypeDef,
  unknown
> = z.object({
  address1: z.string(),
  businessClassification: z.string(),
  businessName: z.string(),
  businessType: z.string(),
  city: z.string(),
  dateOfBirth: z.string().date(),
  ein: z.string(),
  email: z.string(),
  firstName: z.string(),
  ipAddress: z.string().optional(),
  lastName: z.string(),
  postalCode: z.string(),
  ssn: z.string(),
  state: z.string(),
  type: z.string(),
}).describe(
  "Retry Verification for Verified Business Customer (Sole Proprietorship)",
);
