/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type SchemeClientCredentials = {
  clientID: string;
  clientSecret: string;
  tokenURL?: string | undefined;
};

export const SchemeClientCredentials$zodSchema: z.ZodType<
  SchemeClientCredentials,
  z.ZodTypeDef,
  unknown
> = z.object({
  clientID: z.string(),
  clientSecret: z.string(),
  tokenURL: z.string().default("/token"),
});
