/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  SchemeClientCredentials,
  SchemeClientCredentials$zodSchema,
} from "./schemeclientcredentials.js";

export type Security = {
  clientCredentials?: SchemeClientCredentials | undefined;
  bearerAuth?: string | undefined;
};

export const Security$zodSchema: z.ZodType<Security, z.ZodTypeDef, unknown> = z
  .object({
    bearerAuth: z.string().optional(),
    clientCredentials: SchemeClientCredentials$zodSchema.optional(),
  });
