/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type SenderRestrictedErrorLinks = {};

export const SenderRestrictedErrorLinks$zodSchema: z.ZodType<
  SenderRestrictedErrorLinks,
  z.ZodTypeDef,
  unknown
> = z.object({});

export type SenderRestrictedErrorError = {
  code?: string | undefined;
  message?: string | undefined;
  path?: string | undefined;
  _links?: SenderRestrictedErrorLinks | undefined;
};

export const SenderRestrictedErrorError$zodSchema: z.ZodType<
  SenderRestrictedErrorError,
  z.ZodTypeDef,
  unknown
> = z.object({
  _links: z.lazy(() => SenderRestrictedErrorLinks$zodSchema).optional(),
  code: z.string().optional(),
  message: z.string().optional(),
  path: z.string().optional(),
});

export type SenderRestrictedErrorEmbedded = {
  errors?: Array<SenderRestrictedErrorError> | undefined;
};

export const SenderRestrictedErrorEmbedded$zodSchema: z.ZodType<
  SenderRestrictedErrorEmbedded,
  z.ZodTypeDef,
  unknown
> = z.object({
  errors: z.array(z.lazy(() => SenderRestrictedErrorError$zodSchema))
    .optional(),
});

export type SenderRestrictedError = {
  code: string;
  message: string;
  _embedded?: SenderRestrictedErrorEmbedded | undefined;
};

export const SenderRestrictedError$zodSchema: z.ZodType<
  SenderRestrictedError,
  z.ZodTypeDef,
  unknown
> = z.object({
  _embedded: z.lazy(() => SenderRestrictedErrorEmbedded$zodSchema).optional(),
  code: z.string(),
  message: z.string(),
});
