/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type TooManyRequestsError = {
  code?: string | undefined;
  message?: string | undefined;
};

export const TooManyRequestsError$zodSchema: z.ZodType<
  TooManyRequestsError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string().optional(),
  message: z.string().optional(),
});
