/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { HalLink, HalLink$zodSchema } from "./hallink.js";

/**
 * Shared models between all Customer types
 */
export type UnverifiedCustomer = {
  _links?: { [k: string]: HalLink } | undefined;
  id?: string | undefined;
  firstName?: string | undefined;
  lastName?: string | undefined;
  email?: string | undefined;
  type?: string | undefined;
  status?: string | undefined;
  correlationId?: string | undefined;
  created?: string | undefined;
};

export const UnverifiedCustomer$zodSchema: z.ZodType<
  UnverifiedCustomer,
  z.ZodTypeDef,
  unknown
> = z.object({
  _links: z.record(HalLink$zodSchema).optional(),
  correlationId: z.string().optional(),
  created: z.string().datetime({ offset: true }).optional(),
  email: z.string().optional(),
  firstName: z.string().optional(),
  id: z.string().optional(),
  lastName: z.string().optional(),
  status: z.string().optional(),
  type: z.string().optional(),
}).describe("Shared models between all Customer types");
