/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Request body for updating information of an unverified bank funding source
 */
export type UpdateUnverifiedBank = {
  routingNumber?: string | undefined;
  accountNumber?: string | undefined;
  bankAccountType?: string | undefined;
  name: string;
};

export const UpdateUnverifiedBank$zodSchema: z.ZodType<
  UpdateUnverifiedBank,
  z.ZodTypeDef,
  unknown
> = z.object({
  accountNumber: z.string().optional(),
  bankAccountType: z.string().optional(),
  name: z.string(),
  routingNumber: z.string().optional(),
}).describe(
  "Request body for updating information of an unverified bank funding source",
);
