/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Update Unverified Customer or Receive Only User Information
 */
export type UpdateUnverifiedAndReceiveOnly = {
  firstName?: string | undefined;
  lastName?: string | undefined;
  email?: string | undefined;
  businessName?: string | undefined;
};

export const UpdateUnverifiedAndReceiveOnly$zodSchema: z.ZodType<
  UpdateUnverifiedAndReceiveOnly,
  z.ZodTypeDef,
  unknown
> = z.object({
  businessName: z.string().optional(),
  email: z.string().optional(),
  firstName: z.string().optional(),
  lastName: z.string().optional(),
}).describe("Update Unverified Customer or Receive Only User Information");
