/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type UpgradeToVerifiedBusinessAddress = {
  address1: string;
  address2?: string | undefined;
  city: string;
  stateProvinceRegion: string;
  postalCode: string;
  country: string;
};

export const UpgradeToVerifiedBusinessAddress$zodSchema: z.ZodType<
  UpgradeToVerifiedBusinessAddress,
  z.ZodTypeDef,
  unknown
> = z.object({
  address1: z.string(),
  address2: z.string().optional(),
  city: z.string(),
  country: z.string(),
  postalCode: z.string(),
  stateProvinceRegion: z.string(),
});

export type UpgradeToVerifiedBusinessController = {
  firstName: string;
  lastName: string;
  title: string;
  ssn?: string | undefined;
  dateOfBirth: string;
  address: UpgradeToVerifiedBusinessAddress;
};

export const UpgradeToVerifiedBusinessController$zodSchema: z.ZodType<
  UpgradeToVerifiedBusinessController,
  z.ZodTypeDef,
  unknown
> = z.object({
  address: z.lazy(() => UpgradeToVerifiedBusinessAddress$zodSchema),
  dateOfBirth: z.string().date(),
  firstName: z.string(),
  lastName: z.string(),
  ssn: z.string().optional(),
  title: z.string(),
});

/**
 * Upgrade Unverified Customer to Verified Business Customer
 */
export type UpgradeToVerifiedBusiness = {
  firstName: string;
  lastName: string;
  email: string;
  ipAddress?: string | undefined;
  type: string;
  address1: string;
  city: string;
  state: string;
  postalCode: string;
  controller: UpgradeToVerifiedBusinessController;
  businessClassification: string;
  businessType: string;
  businessName: string;
  ein: string;
};

export const UpgradeToVerifiedBusiness$zodSchema: z.ZodType<
  UpgradeToVerifiedBusiness,
  z.ZodTypeDef,
  unknown
> = z.object({
  address1: z.string(),
  businessClassification: z.string(),
  businessName: z.string(),
  businessType: z.string(),
  city: z.string(),
  controller: z.lazy(() => UpgradeToVerifiedBusinessController$zodSchema),
  ein: z.string(),
  email: z.string(),
  firstName: z.string(),
  ipAddress: z.string().optional(),
  lastName: z.string(),
  postalCode: z.string(),
  state: z.string(),
  type: z.string(),
}).describe("Upgrade Unverified Customer to Verified Business Customer");
