/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type WeeklyReceiveLimitReachedErrorLinks = {};

export const WeeklyReceiveLimitReachedErrorLinks$zodSchema: z.ZodType<
  WeeklyReceiveLimitReachedErrorLinks,
  z.ZodTypeDef,
  unknown
> = z.object({});

export type WeeklyReceiveLimitReachedErrorError = {
  code?: string | undefined;
  message?: string | undefined;
  path?: string | undefined;
  _links?: WeeklyReceiveLimitReachedErrorLinks | undefined;
};

export const WeeklyReceiveLimitReachedErrorError$zodSchema: z.ZodType<
  WeeklyReceiveLimitReachedErrorError,
  z.ZodTypeDef,
  unknown
> = z.object({
  _links: z.lazy(() => WeeklyReceiveLimitReachedErrorLinks$zodSchema)
    .optional(),
  code: z.string().optional(),
  message: z.string().optional(),
  path: z.string().optional(),
});

export type WeeklyReceiveLimitReachedErrorEmbedded = {
  errors?: Array<WeeklyReceiveLimitReachedErrorError> | undefined;
};

export const WeeklyReceiveLimitReachedErrorEmbedded$zodSchema: z.ZodType<
  WeeklyReceiveLimitReachedErrorEmbedded,
  z.ZodTypeDef,
  unknown
> = z.object({
  errors: z.array(z.lazy(() => WeeklyReceiveLimitReachedErrorError$zodSchema))
    .optional(),
});

export type WeeklyReceiveLimitReachedError = {
  code: string;
  message: string;
  _embedded?: WeeklyReceiveLimitReachedErrorEmbedded | undefined;
};

export const WeeklyReceiveLimitReachedError$zodSchema: z.ZodType<
  WeeklyReceiveLimitReachedError,
  z.ZodTypeDef,
  unknown
> = z.object({
  _embedded: z.lazy(() => WeeklyReceiveLimitReachedErrorEmbedded$zodSchema)
    .optional(),
  code: z.string(),
  message: z.string(),
});
