/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type WireAccountNotFoundErrorLinks = {};

export const WireAccountNotFoundErrorLinks$zodSchema: z.ZodType<
  WireAccountNotFoundErrorLinks,
  z.ZodTypeDef,
  unknown
> = z.object({});

export type WireAccountNotFoundErrorError = {
  code?: string | undefined;
  message?: string | undefined;
  path?: string | undefined;
  _links?: WireAccountNotFoundErrorLinks | undefined;
};

export const WireAccountNotFoundErrorError$zodSchema: z.ZodType<
  WireAccountNotFoundErrorError,
  z.ZodTypeDef,
  unknown
> = z.object({
  _links: z.lazy(() => WireAccountNotFoundErrorLinks$zodSchema).optional(),
  code: z.string().optional(),
  message: z.string().optional(),
  path: z.string().optional(),
});

export type WireAccountNotFoundErrorEmbedded = {
  errors?: Array<WireAccountNotFoundErrorError> | undefined;
};

export const WireAccountNotFoundErrorEmbedded$zodSchema: z.ZodType<
  WireAccountNotFoundErrorEmbedded,
  z.ZodTypeDef,
  unknown
> = z.object({
  errors: z.array(z.lazy(() => WireAccountNotFoundErrorError$zodSchema))
    .optional(),
});

export type WireAccountNotFoundError = {
  code: string;
  message: string;
  _embedded?: WireAccountNotFoundErrorEmbedded | undefined;
};

export const WireAccountNotFoundError$zodSchema: z.ZodType<
  WireAccountNotFoundError,
  z.ZodTypeDef,
  unknown
> = z.object({
  _embedded: z.lazy(() => WireAccountNotFoundErrorEmbedded$zodSchema)
    .optional(),
  code: z.string(),
  message: z.string(),
});
