/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type WireAccountRestrictedErrorLinks = {};

export const WireAccountRestrictedErrorLinks$zodSchema: z.ZodType<
  WireAccountRestrictedErrorLinks,
  z.ZodTypeDef,
  unknown
> = z.object({});

export type WireAccountRestrictedErrorError = {
  code?: string | undefined;
  message?: string | undefined;
  path?: string | undefined;
  _links?: WireAccountRestrictedErrorLinks | undefined;
};

export const WireAccountRestrictedErrorError$zodSchema: z.ZodType<
  WireAccountRestrictedErrorError,
  z.ZodTypeDef,
  unknown
> = z.object({
  _links: z.lazy(() => WireAccountRestrictedErrorLinks$zodSchema).optional(),
  code: z.string().optional(),
  message: z.string().optional(),
  path: z.string().optional(),
});

export type WireAccountRestrictedErrorEmbedded = {
  errors?: Array<WireAccountRestrictedErrorError> | undefined;
};

export const WireAccountRestrictedErrorEmbedded$zodSchema: z.ZodType<
  WireAccountRestrictedErrorEmbedded,
  z.ZodTypeDef,
  unknown
> = z.object({
  errors: z.array(z.lazy(() => WireAccountRestrictedErrorError$zodSchema))
    .optional(),
});

export type WireAccountRestrictedError = {
  code: string;
  message: string;
  _embedded?: WireAccountRestrictedErrorEmbedded | undefined;
};

export const WireAccountRestrictedError$zodSchema: z.ZodType<
  WireAccountRestrictedError,
  z.ZodTypeDef,
  unknown
> = z.object({
  _embedded: z.lazy(() => WireAccountRestrictedErrorEmbedded$zodSchema)
    .optional(),
  code: z.string(),
  message: z.string(),
});
