/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type WithdrawRtpPersonalWithdrawalNotSupportedErrorLinks = {};

export const WithdrawRtpPersonalWithdrawalNotSupportedErrorLinks$zodSchema:
  z.ZodType<
    WithdrawRtpPersonalWithdrawalNotSupportedErrorLinks,
    z.ZodTypeDef,
    unknown
  > = z.object({});

export type WithdrawRtpPersonalWithdrawalNotSupportedErrorError = {
  code?: string | undefined;
  message?: string | undefined;
  path?: string | undefined;
  _links?: WithdrawRtpPersonalWithdrawalNotSupportedErrorLinks | undefined;
};

export const WithdrawRtpPersonalWithdrawalNotSupportedErrorError$zodSchema:
  z.ZodType<
    WithdrawRtpPersonalWithdrawalNotSupportedErrorError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    _links: z.lazy(() =>
      WithdrawRtpPersonalWithdrawalNotSupportedErrorLinks$zodSchema
    ).optional(),
    code: z.string().optional(),
    message: z.string().optional(),
    path: z.string().optional(),
  });

export type WithdrawRtpPersonalWithdrawalNotSupportedErrorEmbedded = {
  errors?:
    | Array<WithdrawRtpPersonalWithdrawalNotSupportedErrorError>
    | undefined;
};

export const WithdrawRtpPersonalWithdrawalNotSupportedErrorEmbedded$zodSchema:
  z.ZodType<
    WithdrawRtpPersonalWithdrawalNotSupportedErrorEmbedded,
    z.ZodTypeDef,
    unknown
  > = z.object({
    errors: z.array(
      z.lazy(() =>
        WithdrawRtpPersonalWithdrawalNotSupportedErrorError$zodSchema
      ),
    ).optional(),
  });

export type WithdrawRtpPersonalWithdrawalNotSupportedError = {
  code: string;
  message: string;
  _embedded?:
    | WithdrawRtpPersonalWithdrawalNotSupportedErrorEmbedded
    | undefined;
};

export const WithdrawRtpPersonalWithdrawalNotSupportedError$zodSchema:
  z.ZodType<
    WithdrawRtpPersonalWithdrawalNotSupportedError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    _embedded: z.lazy(() =>
      WithdrawRtpPersonalWithdrawalNotSupportedErrorEmbedded$zodSchema
    ).optional(),
    code: z.string(),
    message: z.string(),
  });
