/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type WithdrawInvalidAmountForClearingTypeErrorLinks = {};

export const WithdrawInvalidAmountForClearingTypeErrorLinks$zodSchema:
  z.ZodType<
    WithdrawInvalidAmountForClearingTypeErrorLinks,
    z.ZodTypeDef,
    unknown
  > = z.object({});

export type WithdrawInvalidAmountForClearingTypeErrorError = {
  code?: string | undefined;
  message?: string | undefined;
  path?: string | undefined;
  _links?: WithdrawInvalidAmountForClearingTypeErrorLinks | undefined;
};

export const WithdrawInvalidAmountForClearingTypeErrorError$zodSchema:
  z.ZodType<
    WithdrawInvalidAmountForClearingTypeErrorError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    _links: z.lazy(() =>
      WithdrawInvalidAmountForClearingTypeErrorLinks$zodSchema
    ).optional(),
    code: z.string().optional(),
    message: z.string().optional(),
    path: z.string().optional(),
  });

export type WithdrawInvalidAmountForClearingTypeErrorEmbedded = {
  errors?: Array<WithdrawInvalidAmountForClearingTypeErrorError> | undefined;
};

export const WithdrawInvalidAmountForClearingTypeErrorEmbedded$zodSchema:
  z.ZodType<
    WithdrawInvalidAmountForClearingTypeErrorEmbedded,
    z.ZodTypeDef,
    unknown
  > = z.object({
    errors: z.array(
      z.lazy(() => WithdrawInvalidAmountForClearingTypeErrorError$zodSchema),
    ).optional(),
  });

export type WithdrawInvalidAmountForClearingTypeError = {
  code: string;
  message: string;
  _embedded?: WithdrawInvalidAmountForClearingTypeErrorEmbedded | undefined;
};

export const WithdrawInvalidAmountForClearingTypeError$zodSchema: z.ZodType<
  WithdrawInvalidAmountForClearingTypeError,
  z.ZodTypeDef,
  unknown
> = z.object({
  _embedded: z.lazy(() =>
    WithdrawInvalidAmountForClearingTypeErrorEmbedded$zodSchema
  ).optional(),
  code: z.string(),
  message: z.string(),
});
