/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type WithdrawInvalidWireBeneficiaryCountryErrorLinks = {};

export const WithdrawInvalidWireBeneficiaryCountryErrorLinks$zodSchema:
  z.ZodType<
    WithdrawInvalidWireBeneficiaryCountryErrorLinks,
    z.ZodTypeDef,
    unknown
  > = z.object({});

export type WithdrawInvalidWireBeneficiaryCountryErrorError = {
  code?: string | undefined;
  message?: string | undefined;
  path?: string | undefined;
  _links?: WithdrawInvalidWireBeneficiaryCountryErrorLinks | undefined;
};

export const WithdrawInvalidWireBeneficiaryCountryErrorError$zodSchema:
  z.ZodType<
    WithdrawInvalidWireBeneficiaryCountryErrorError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    _links: z.lazy(() =>
      WithdrawInvalidWireBeneficiaryCountryErrorLinks$zodSchema
    ).optional(),
    code: z.string().optional(),
    message: z.string().optional(),
    path: z.string().optional(),
  });

export type WithdrawInvalidWireBeneficiaryCountryErrorEmbedded = {
  errors?: Array<WithdrawInvalidWireBeneficiaryCountryErrorError> | undefined;
};

export const WithdrawInvalidWireBeneficiaryCountryErrorEmbedded$zodSchema:
  z.ZodType<
    WithdrawInvalidWireBeneficiaryCountryErrorEmbedded,
    z.ZodTypeDef,
    unknown
  > = z.object({
    errors: z.array(
      z.lazy(() => WithdrawInvalidWireBeneficiaryCountryErrorError$zodSchema),
    ).optional(),
  });

export type WithdrawInvalidWireBeneficiaryCountryError = {
  code: string;
  message: string;
  _embedded?: WithdrawInvalidWireBeneficiaryCountryErrorEmbedded | undefined;
};

export const WithdrawInvalidWireBeneficiaryCountryError$zodSchema: z.ZodType<
  WithdrawInvalidWireBeneficiaryCountryError,
  z.ZodTypeDef,
  unknown
> = z.object({
  _embedded: z.lazy(() =>
    WithdrawInvalidWireBeneficiaryCountryErrorEmbedded$zodSchema
  ).optional(),
  code: z.string(),
  message: z.string(),
});
